### ISSUE TITLE
[Bug] HTML Text not working properly

### ISSUE THREAD

**Issue by leo-adm** [xamarin/Xamarin.Forms#10012]
### Description
HTML strike property isn't applying to Label in Android5.0 and also HTML strike and superscripted properties aren't applying to UWP. I've tried strike, s and del tag and none worked. Also tried to set the text in code behind and in xaml. See:

       <StackLayout>
            <Label TextType="Html" Text="&lt;u &gt;Underline Text&lt;/u&gt;"/>
            <Label TextType="Html" Text="&lt;i &gt;Italic Text&lt;/i&gt;"/>
            <Label TextType="Html" Text="&lt;sup &gt;Superscripted &lt;/sup&gt; Text"/>
            <Label TextType="Html" Text="&lt;b &gt;Bold Text&lt;/b&gt;"/>            
            <Label TextType="Html" Text="&lt;s &gt;Strike Text - s tag&lt;/s&gt;"/>
            <Label TextType="Html" Text="&lt;strike &gt;Strike Text - strike tag&lt;/strike&gt;"/>
            <Label TextType="Html" Text="&lt;del &gt;Strike Text - del tag&lt;/del&gt;"/>
        </StackLayout>

### Steps to Reproduce
Run reproduction link or add the stacklayout above to a project

### Expected Behavior
Text apply the changes
### Actual Behavior
Text stays normal
### Basic Information

- Version with issue: XF 4.3-4.5
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  Not tested
  - Android: 5.0
  - UWP:  16299 
- Affected Devices:
Moto E 2gen 4g Plus

### Screenshots

On UWP:

![image](https://user-images.githubusercontent.com/40642381/76965713-89722900-6903-11ea-9364-96748cef6ed9.png)

On Android 5.0:

![image](https://user-images.githubusercontent.com/40642381/76968806-42d2fd80-6908-11ea-99a1-2a85a25150e2.png)

### Reproduction Link

[BugHTML.zip](https://github.com/xamarin/Xamarin.Forms/files/4349367/BugHTML.zip)

### Workaround
Use formatted text

**Comment by jfversluis** [comment]
As noted in [the documentation](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/label#display-html) only the tags that are supported on the underlaying OS are supported in Forms. I think the majority of the tags was only added from Android API 24 and up. Running this sample on an emulator of that version indeed shows that it works.

For UWP we have implemented some manual parsing because showing HTML directly in a control is not supported on the platform. I'll keep this as a bug, there might be possibilities to implement this that we can investigate.

**Comment by transis2** [comment]
Any news on this ?

**Comment by MixaNir** [comment]
The same issue on iOS (tested versions 13.7, 14.1 and 12.4.7).
![image](https://user-images.githubusercontent.com/26028899/98257434-bd808400-1f90-11eb-8d4f-ce81fcf204fa.png)
Expected (as on android):
![image](https://user-images.githubusercontent.com/26028899/98257513-cffabd80-1f90-11eb-9561-c89fcf4ddaad.png)

**Comment by GrmpyPmpkin** [comment]
Hi, I was wondering if anyone has any ideas on how to get superscript to work on UWP.

**Comment by eblahimanshu** [comment]
Hi, I am facing still the same issue in Arabic text with the type HTML. The application is freezing completely. No exceptions nothing from the visual studio even. Please advise. Seems the Microsoft team skipped this issue or is not interested in enhancing and fixing issues in UWP.

**Comment by isax5** [comment]
Same problem!

**Comment by eblahimanshu** [comment]
I will recommend you one way to implement it. Implement the Html Agility pack. It will convert the HTML to text (paragraphs, headings etc.) And you can use that text. It is almost in the same format. 
HTML Agility package : https://www.nuget.org/packages/HtmlAgilityPack/
