### ISSUE TITLE
iOS Frame IsClippedToBounds broken [Bug] 

### ISSUE THREAD

**Issue by taublast** [xamarin/Xamarin.Forms#11091]
### Description

After upgrading from Forms from 4.6.0.726 to 4.6.0.967
frames on *iOS* stopped clipping content, tested with a grid inside.

**Edit: Last good version checked 4.6.0.847 is okay.**

### Steps to Reproduce

```
<frame    CornerRadius="something"     IsClippedToBounds="True">
    <grid>
    <image/><or whatever/>
    </grid>
<frame>
```

Please kindly check here:
https://forums.xamarin.com/discussion/comment/414472

### Expected Behavior

frame to clip content while IsClippedToBounds="True"

### Actual Behavior

Not clipping content while IsClippedToBounds="True"

### Basic Information

- Version with issue: Forms 4.6.0.967
- Last known good version: 4.6.0.847
- IDE: VS 2019 16.6.2
- Platform Target Frameworks: 
  - iOS:  latest.. no idea where to check the version when developing from windows

### Screenshots

![image](https://user-images.githubusercontent.com/25801194/84914675-8afaeb00-b0c4-11ea-9e47-ed1d9c703d9c.png)

### Reproduction Link

https://forums.xamarin.com/discussion/comment/414472 confirmed by xamarin staff, LeonLu.

### Workaround

credits to LeonLu

 ```
 [assembly: ExportRenderer(typeof(Frame), typeof(FrameFix))]
    namespace Your.iOS.Renderers
    {
        protected override void OnElementChanged(ElementChangedEventArgs<Frame> e)
        {
            base.OnElementChanged(e);

            if (e.OldElement != null && Control != null)
            {
                Control.PropertyChanged -= OnControlPropertyChanged;
            }

            if (e.NewElement!=null && NativeView != null)
            {
                Control = e.NewElement;
                Control.PropertyChanged += OnControlPropertyChanged;
                
                UpdateCorners();
            }
        }

        protected void UpdateCorners()
        {
            NativeView.Layer.AllowsEdgeAntialiasing = true;
            NativeView.Layer.MasksToBounds = Control.IsClippedToBounds;
            NativeView.Layer.CornerRadius = Control.CornerRadius;
        }

        private void OnControlPropertyChanged(object sender, PropertyChangedEventArgs e)
        {
            if (NativeView == null || Control == null)
                return;

            if (e.PropertyName == "IsClippedToBounds" 
                || e.PropertyName == "CornerRadius")
            {
                UpdateCorners();
            }
        }
    }
```

**Comment by Codelisk** [comment]
Already solved in nightly build version Xamarin.Forms nighly build 4.8.0.908

**Comment by MSiccDev** [comment]
Just adding that UWP also works, it is really only iOS.

**Comment by thisisthekap** [comment]
Is this one going to be fixed on 4.6.0?

**Comment by knasher** [comment]
I've just upgraded to 4.7.1080 and this behaviour is still happening; the [release notes](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/release-notes/4.7/4.7.0-sr1#wednesday-july-1-2020---xamarinforms-4701080-470-service-release-1) mentioned there was a fix for #11031

**Comment by samhouts** [comment]
closed by #11129
