### ISSUE TITLE
Forms version 4.7.0.1179 back button in navigation page is now missing on Android

### ISSUE THREAD

**Issue by Nerves82** [xamarin/Xamarin.Forms#11553]
### Description

In previous version of Xamarin Forms Shell, if a view is navigated to using .PushAsync() it would have a back arrow in the navigation bar at the top left. The back button is now missing on these views. In conjunction with this, in the previous version of Forms the hamburger/flyout button would always be visible on the root while using Shell despite having the FlyoutBehavior flag set too false. Now that is missing as well, which is a good thing because that means that setting the flag to false is now working, but the back button is missing. 

### Expected Behavior

Navigate to a Content Page with Navigation.Push(new Page()): and get a nav bar with a back button. 

### Actual Behavior

Back button is missing.

### Basic Information

- Version with issue: 4.7.0.1179
- Last known good version: 4.7.0.1142
- IDE: VSMac, Jetbrains Rider
- Platform Target Frameworks: 
  - Android: 7.0
- Affected Devices: Samsung SM-T813

### Screenshots

![AA03AFDF-E830-44A4-BCA1-A3FF1D0924ED](https://user-images.githubusercontent.com/5743074/88440149-21fd4600-cddb-11ea-9332-7d6634c350aa.jpeg)
![FD0EB84F-83F3-40A6-87A6-EFDD45D582D8](https://user-images.githubusercontent.com/5743074/88440210-4c4f0380-cddb-11ea-9e77-8b5ba17d658d.jpeg)

**Comment by PureWeen** [comment]
This should be fixed by this PR

https://github.com/xamarin/Xamarin.Forms/pull/11526

**Comment by PureWeen** [comment]
@Nerves82 can you elaborate on this? 

> the hamburger/flyout button would always be visible on the root while using Shell despite having the FlyoutBehavior flag set too false.

**Comment by Nerves82** [comment]
Sure. On android the root view will always have the hamburger menu button showing despite not having master/details set up in the app. I am using a mix of Shell and regular navigation since Shell is too unreliable at the moment to depend on for all my navigation. So my root view is set in Shell and it is a simple content page so gets the backing navigation controller that shell gives it (I think that is the way it works). On iOS the flag works and the menu button is not shown, on android it is visible and clickable and calls my Shell.BackButtonBehaviour override. I need to have the navigation bar visible for other controls so that is why I am relying on hiding the button. Not sure why it is there in the first place, I do not have Flyout or Master/Detail set up at all.

**Comment by PureWeen** [comment]
>  Shell is too unreliable at the moment to depend on for all my navigation

Can you elaborate on this? :-)


Can you test the following nuget and let me know if it acts how you're expecting it to?

[Xamarin.Forms.4.7.0.4072.nupkg.zip](https://github.com/xamarin/Xamarin.Forms/files/4974508/Xamarin.Forms.4.7.0.4072.nupkg.zip)

**Comment by Nerves82** [comment]
I tried going full shell for all navigation, which is very simple in my app. Its all push and pop using relative navigation but discovered that passing arguments is not supported for relative. So I moved to absolute navigation so I could pass arguments. During my sign in flow I need to basically do the equivalent of "MainPage = new whatever" when navigation from my log in flow to the main app flow. I tried having a blank "loading view" as my root so I could pop off my log in and then replace it, but it ended up failing because I would get a few different exceptions (I forget what they were ATM) when using 
Shell.Current.GoToAsync($"//../{nameof(SomePage)}"); to accomplish it. I also did not like that I could only pass strings during navigation. With Navigation.PushAsync() I can instantiate my view and view model and hydrate it with anything I need to. At the time Shell was just too buggy and limited and some of those limitation (such as no passing values with relative navigation) where not in the documentation or noted in exceptions so I was just left wondering. I'll give at another try when it matures more.

**Comment by PureWeen** [comment]
> Its all push and pop using relative navigation, but I discovered that passing arguments is not supported for relative.

This isn't accurate. Can you create a new issue if this is what you are seeing?

> During my sign in flow I need to basically do the equivalent of "MainPage = new whatever" when navigation from my log in flow to the main app flow. I tried having a blank "loading view" as my root so I could pop off my log in and then replace it, but it ended up failing because I would get a few different exceptions (I forget what they were ATM) when using
Shell.Current.GoToAsync($"//../{nameof(SomePage)}"); to accomplish it. 

Check out my sample here that I'm pretty sure does exactly what you're saying

https://github.com/PureWeen/ShellTemplate

> I also did not like that I could only pass strings during navigation

Yea my plan is to adjust this for 5.0

**Comment by alanwol** [comment]
I'm having the same issue, will this be solved in the next stable release? I removed the FlyOut from my shell app but the backbutton worked in the previous version.

**Comment by Nerves82** [comment]
> > Its all push and pop using relative navigation, but I discovered that passing arguments is not supported for relative.
> 
> This isn't accurate. Can you create a new issue if this is what you are seeing?

As of 30 days ago this was accurate. Has it been added recently?

https://stackoverflow.com/questions/62586261/adding-a-query-to-gotoasync-uri-navigation-in-xamarin-forms-shell-causes-it-to-s

**Comment by PureWeen** [comment]
@Nerves82 Parameters on relative routes has always worked 

I commented on that SO post

https://stackoverflow.com/questions/62586261/adding-a-query-to-gotoasync-uri-navigation-in-xamarin-forms-shell-causes-it-to-s#comment111302129_62587419

Junior Jiang is wrong and I'll talk to them about modifying that answer

So either
1) the user was just doing it wrong
2) there's a bug
3) it was fixed by the PR for this issue https://github.com/xamarin/Xamarin.Forms/issues/11220

With that latest 4.7 if you can demonstrate it not working that would be really helpful so I can fix the scenario or we can see what you're doing incorrectly

**Comment by Nerves82** [comment]
Ok, at some point I will give it another go. Glad to know it is in there.

**Comment by mohsen-mohamed** [comment]
i have the same issue but for iOS 
the back button is hidden for iOS but is visible on android correctly 
i'm using XF version 4.8.0.1451

**Comment by divyanshuatsakhaglobal** [comment]
Any update on this. Back button still not showing in the version 5.0.0.2515
