### ISSUE TITLE
[Bug] 4.8.0 UWP throws Layout cycle detected. Layout could not complete.

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/Xamarin.Forms#11680]
### Description

I have just upgraded to 4.8.0 version and ran the existing app in uwp and it crashed instantly with this "Layout cycle detected.  Layout could not complete." without more information. I am guessing that it is most probably with CollectionView related because I tried another existing app which doesnt use CollectionView at all and it works fine. 
 
### Steps to Reproduce
1. add a TitleView with a contentview
2. ContentView has   SizeChanged="OnSizeChanged" event
3. Try to update titleView within OnSizeChanged event

###Last know working version: 4.7

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by YZahringer** [comment]
I have the same error after upgrade from `4.8.0.1534` to `5.0.0.1539-pre2`. 

It's related to `TitleView`, if I remove it, the app works. Can be reproduced updating [this project](https://github.com/MADSENSE/Madsense.XamarinForms.Sample/tree/uwp-push-navigationPageTitle) to XF version `5.0.0.1539-pre2`.

**Comment by BurkusCat** [comment]
@samhouts I think this potentially needs opened again. I am seeing this exception on Xamarin Forms 5. Some of my ContentViews appear to be causing the exception. I haven't been able to narrow it down further yet though.

**Comment by hartez** [comment]
This should be fixed from 5.0.0-pre3 onward - it was addressed in #12365.

If I update the project linked by @YZahringer to pre3 or later, it no longer crashes.

@BurkusCat are you using a TitleView in your project?

**Comment by BurkusCat** [comment]
@hartez I am using the same TitleView on most pages in the app. Only some pages in the app crash when I visit them. The pages are inside a MasterDetailPage. I tried removing the TitleView from these pages but I still get the crash.

The exception:
![image](https://user-images.githubusercontent.com/7528322/104005216-b1858e00-519c-11eb-9597-54e703afec84.png)

The title view with content view:
``` xaml
    <NavigationPage.TitleView>
        <views:HeaderNav />
    </NavigationPage.TitleView>
```

On one of the simpler pages that crashes, if I remove the `SfListView` it resolves the issue. This `SfListView` is in a `Grid` which is in a `ScrollView`. Simplifying the layout to just the SfListView also fixes the crash (I don't really want to do that though as I need other controls on the page).

``` xaml
                <syncfusion:SfListView
                    AllowSwiping="False"
                    AutoFitMode="Height"
                    IsScrollingEnabled="False"
                    ItemSize="51"
                    ItemsSource="{Binding Items}"
                    SelectionBackgroundColor="White"
                    VerticalOptions="Start">
                    <syncfusion:SfListView.Behaviors>
                        <prismLibrary:EventToCommandBehavior
                            Command="{Binding GoToItemCommand}"
                            EventArgsConverter="{StaticResource SfItemTappedEventArgsConverter}"
                            EventName="ItemTapped" />
                    </syncfusion:SfListView.Behaviors>
                    <syncfusion:SfListView.ItemTemplate>
                        <DataTemplate>
                            <ViewCell IsEnabled="False">
                                <Frame
                                    Margin="0"
                                    Padding="15"
                                    BorderColor="Black"
                                    CornerRadius="0">
                                    <StackLayout>
                                        <Label
                                            LineBreakMode="NoWrap"
                                            Text="{Binding CreatedDate, Converter={StaticResource DateTimeConverter}}"
                                            VerticalOptions="CenterAndExpand" />
                                        <Label
                                            LineBreakMode="TailTruncation"
                                            MaxLines="2"
                                            Text="{Binding Entry}"
                                            VerticalOptions="CenterAndExpand" />
                                    </StackLayout>
                                </Frame>
                            </ViewCell>
                        </DataTemplate>
                    </syncfusion:SfListView.ItemTemplate>
                </syncfusion:SfListView>
```

- I am on Xamarin.Forms v5.0.0.1874 where I get the issue.
- I downgraded to v4.8.0.1269 - no issue.
- v4.8.0.1821 works fine.
- v5.0.0.1487-pre1 <-- strange things happen with the flyout menu staying popped out but it doesn't crash (this appears to be fixed in later versions)
- **v5.0.0.1539-pre2** <-- this is where the regression happens. This build is where we start getting crashes throughout the app.

**Comment by rmarinho** [comment]
Hi @BurkusCat  we will need a repro project to look at this issue. Please upload a small sample.

Thanks

**Comment by BurkusCat** [comment]
Hi @rmarinho,
Here is a small sample. As an example, going from 5.0.0.2012 --> 4.8.0.1821 fixes the crash:
[Xamarin5UWPCrash.zip](https://github.com/xamarin/Xamarin.Forms/files/6054707/Xamarin5UWPCrash.zip)

I wasn't able to get great debug info from it (maybe because its the startup page)
![image](https://user-images.githubusercontent.com/7528322/109391073-2eb3c080-790d-11eb-8f08-6f69e4a4fc30.png)

Thanks,
Ronan

**Comment by PureWeen** [comment]
@BurkusCat did you log a bug with SyncFusion by chance? It might be a little bit tricky to debug this one since it's using a SyncFusion control

**Comment by BurkusCat** [comment]
@PureWeen I have created a SyncFusion bug here: https://www.syncfusion.com/feedback/23086/sflistview-crashes-when-moving-from-xamarin-forms-4-8-xamarin-forms-5-0-uwp

The SyncFusion ticket should be public for comments if there are any questions/details you need to ask.

**Comment by jfversluis** [comment]
@BurkusCat I see that SyncFusion released an update. Did that fix it?

@EmilAlipiev if this is fixed for SyncFusion is there still something affecting you?

**Comment by EmilAlipiev** [comment]
I need to check that again but i believe that error is no longer reproducible

**Comment by jfversluis** [comment]
If you would be willing to check I would really appreciate that and send you a slice of virtual cake!

**Comment by BurkusCat** [comment]
@jfversluis I was moved off of the project that was affected before SyncFusion released a fix so I won't be able to verify this one.

**Comment by jfversluis** [comment]
@EmilAlipiev did you have an opportunity to check? In fact, I'll close this one for now. Let me know if there is still an issue
