### ISSUE TITLE
[Bug] CollectionView shows both EmptyView and Footer on iOS

### ISSUE THREAD

**Issue by sthch** [xamarin/Xamarin.Forms#13212]
### Description
If the CollectionView contains zero elements, both EmptyView and Footer will display on iOS. But with same situation on Android, only EmptyView will be shown.

### Steps to Reproduce
1. Create a CollectionView, binding ItemsSource to an empty ObservableCollection, set both EmptyView and Footer with a Label.
2. Run the application on both Android and iOS platform.

### Expected Behavior
Only the EmptyView displayed.
![微信截图_20201222143324](https://user-images.githubusercontent.com/18411241/102859408-cf49b800-4466-11eb-975a-e4f5d7c27d5b.png)

### Actual Behavior
Both EmptyView and Footer are displayed on iOS。
![微信截图_20201222143229](https://user-images.githubusercontent.com/18411241/102859444-de306a80-4466-11eb-9936-2ee595d7453c.png)

### Basic Information
- Version with issue: 5.0-pre5
- Platform Target Frameworks: 
  - iOS:  14.3
  - Android: 11

### Code sample
`            <CollectionView ItemsSource="{Binding News}" VerticalScrollBarVisibility="Never" RemainingItemsThreshold="2" RemainingItemsThresholdReachedCommand="{Binding LoadMoreNewsCommand}">
                <CollectionView.ItemsLayout>
                    <LinearItemsLayout Orientation="Vertical" ItemSpacing="0" />
                </CollectionView.ItemsLayout>
                <CollectionView.EmptyView>
                    <StackLayout>
                        <Label Text="暂无数据" TextColor="#BCBCBC" FontSize="13" HorizontalOptions="Center" Padding="0,20,0,15" />
                    </StackLayout>
                </CollectionView.EmptyView>
                <CollectionView.Footer>
                    <StackLayout>
                        <Label Text="没有更多了~" TextColor="#CCCCCC" FontSize="13" HorizontalOptions="Center" Padding="0,20,0,15" />
                    </StackLayout>
                </CollectionView.Footer>
            </CollectionView>`

**Comment by Tommigun1980** [comment]
Same goes for Header on iOS (didn't test on other platforms), ie it will always display the header, even when the EmptyView is shown (so both the header and empty view contents will overlap).

**Comment by Tommigun1980** [comment]
Repro: [Issue13212.zip](https://github.com/xamarin/Xamarin.Forms/files/5742627/Issue13212.zip)

Screenshot of the error (EmptyView, Header and Footer are all displayed at the same time when there are no elements. Expected: Only EmptyView should be displayed):
<img width="560" alt="Screenshot 2020-12-26 at 4 52 13" src="https://user-images.githubusercontent.com/60286968/103144683-4a94bd80-4736-11eb-9cda-950413d59712.png">

**Comment by hartez** [comment]
The correct behavior for the CollectionView is to _always_ display the Header and Footer (if present), and to _also_ display the EmptyView if the ItemsSource is empty.

One of the 5.0.0 pre-releases introduced a bug where the EmptyView overlapped the Header; this was fixed by #13247.

**Comment by sthch** [comment]
> The correct behavior for the CollectionView is to _always_ display the Header and Footer (if present), and to _also_ display the EmptyView if the ItemsSource is empty.
> 
> One of the 5.0.0 pre-releases introduced a bug where the EmptyView overlapped the Header; this was fixed by #13247.

Hi, hartez, thanks for your reply. But I still have a question.
If "The correct behavior for the CollectionView is to always display the Header and Footer", than why there is only EmptyView has shown on the Android platform? Is that another bug?

**Comment by Tommigun1980** [comment]
Hi @hartez, I also have a question.

if the intended behavior is to always show header and footer then at least I can’t see much use for the EmptyView.
I would like to use the EmptyView as an up sell to do whatever action is needed to get content into it, but if the header and footer are always displayed it’s useless to me.
I can’t think of a lot of cases where the header and footer make sense when there’s no content, so why not at least make that toggleable? You suggested the EmptyView to me for the upswell but unfortunately it’s no use at least to me with the current behavior.

Thanks.

**Comment by Tommigun1980** [comment]
> > The correct behavior for the CollectionView is to _always_ display the Header and Footer (if present), and to _also_ display the EmptyView if the ItemsSource is empty.
> > One of the 5.0.0 pre-releases introduced a bug where the EmptyView overlapped the Header; this was fixed by #13247.
> 
> Hi, hartez, thanks for your reply. But I still have a question.
> If "The correct behavior for the CollectionView is to always display the Header and Footer", than why there is only EmptyView has shown on the Android platform? Is that another bug?

@sthch Would you mind reposting this issue and link to this report here as I’m not sure if they get notifications from closed issues? Thanks a million!

**Comment by sthch** [comment]
@Tommigun1980 Issue created.
:)
