### ISSUE TITLE
[Bug] [iOS] Xamarin Hot Restart - Default template app crashes on startup

### ISSUE THREAD

**Issue by ebrodlic** [xamarin/Xamarin.Forms#13759]
### Description
Trying to run the template Xamarin app via Visual Studio (Win 10) using hot restart results in app crashing as soon as its started. (Before the debugger is able to attach).

### Steps to Reproduce

1. Create a new Xamarin project targeting iOS (tried tabbed and blank)
2. Press F5 (debug profile) and set up hot restart automatic provisioning
3. Wait until the build and copy to device is completed, until a popup shows with the message "launch the application on the device to continue"
4. Launch the app on the device, see the Xamarin splash followed by an immediate app crash 

### Expected Behavior
Application starts up, shows the home page with an active debug session running.

### Actual Behavior
Application crashes right away, before the debugging can pick anything up.

### Basic Information

- Version with issue: Xamarin.Forms v4.8.0.1451, v5.0.0.2012
- Platform Target Frameworks: 
  - iOS:  SDK Version: Default, Deployment Target: 8-14 (same issue)
- NuGet Packages: 
  - Xamarin.Forms v4.8.0.1451, Xamarin.Essentials v1.5.3.2 
  - Xamarin.Forms v5.0.0.2012, Xamarin.Essentials v1.6.1
- Affected Devices: iPhone XS (iOS 14.4)

### Environment

Visual Studio: Microsoft Visual Studio Community 2019 - 16.8.5

<details><summary>Show/Hide Visual Studio info</summary>

```
Microsoft Visual Studio Community 2019
Version 16.8.5
VisualStudio.16.Release/16.8.5+31005.135
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA872
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.8.559.8768
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2052803+84e121f1403378489b842e1797df2f3f5a49ac3c
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.8.559.8768
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.8.559.8768
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.8.559.8768
Azure Functions and Web Jobs Tools

C# Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30924.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.8.43 (00471f8)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.8.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62102.01130
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   16.0.21016.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Unity   4.8.2.0
Visual Studio Tools for Unity

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.8.000.262 (d16-8@4d60f9c)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.8.0.507 (remotes/origin/d16-8@e87b24884)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.8.112 (86385a3)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.1.0.26 (d16-8/a36ce73)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 5e9cb6d
    Java.Interop: xamarin/java.interop/d16-8@79d9533
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc


Xamarin.iOS and Xamarin.Mac SDK   14.10.0.4 (5a05865f6)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

</details>

> VS bug [#1280537](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1280537)

**Comment by sebastianszaniszlo** [comment]
This happens to me as well. I thought I was going insane for a second. Do we know what might be the cause for this?

**Comment by ebrodlic** [comment]
It seems to be one of those pesky issues that affect only a few cases, making it hard to figure out. My guess is something device specific, or we are missing some important set up Apple side, but no idea.

So far I've seen:
- This guy in the discussion has a very similar issue: #13644
- MSFT representative commenting that everything is fine on their end with a similar setup, so it has to be a configuration or a local device difference: [Question](https://docs.microsoft.com/en-us/answers/questions/282918/xamarin-template-app-crashing-on-my-iphone-via-hot.html?childToView=288406#comment-288406)

**Comment by inimrdecesaris** [comment]
I'm also having the same issue. Building and deploying the app through Hot Restart from VS Professional 2019 (16.8.6) on Windows 10 to an iPhone 6s (iOS 14.4) seems to work perfectly, but the app immediately crashes after showing the launch screen.

**Comment by Nathan-Rozendaal** [comment]
Got the same issue, also on an iPhone 6s, and an iPhone 5s with hot restart on Windows 10.

**Comment by Siphonophora** [comment]
I'm having this issue on an iPhone 6s as well. I posted details on the microsoft Q&A page about steps I have taken. https://docs.microsoft.com/en-us/answers/questions/293841/getting-started-ios-app-crashes-on-launch.html

**Comment by ebrodlic** [comment]
Any chance this is related to S series of devices?
Does anyone have a spare device to compare behaviour?

**Comment by ebrodlic** [comment]
Apologies for close/reopen, accidentally closed the issue with phone app.

**Comment by Siphonophora** [comment]
@ebrodlic So, i don't think S is really a distinct product line. From what I recall it was just part of apple's Tic-Tock product cycle. 

I did go ahead and factory reset this phone to a clean install of iOS 14.4. All I did before deploying the xamarin app was to sign into icloud. The app still crashed right after hitting the splash screen. 

I'm hoping to borrow another device for more testing and will add to this if I learn anything new

**Comment by mcooper-bits** [comment]
Having the same issue with a regular iPhone 6, app crashes immediately when starting.

**Comment by ebrodlic** [comment]
Does anyone have a mac and is able to get any OS logs when the crash happens?

Or if one has tips on collecting relevant info, I might be able to inspect the crash using my friends mac.

**Comment by PureWeen** [comment]
@mauroa @emaf  ?

**Comment by emaf** [comment]
Hi all, 
This is a problem with a change Apple made on the certificates used to sign the app, and we're working on a fix. Since this is a problem on Visual Studio it's being tracked on the Developer Community: https://developercommunity2.visualstudio.com/t/Xamarin-forms-application-deployed-with-/1338291.

**Comment by ebrodlic** [comment]
Thanks for chipping in! @emaf 
Will keep an eye on the devcom thread.

**Comment by Siphonophora** [comment]
@emaf Any idea of the scope, if its just older iphones on iOS 14.4 or all devices? Thanks!

**Comment by ebrodlic** [comment]
@Siphonophora think this is across all devices if it is related to app signing?
I have an XS which is not **that** old and suffer the same issue.
Then again, the MSFT representative tested with an X and it seemed to work fine, so not sure whats going on there

**Comment by emaf** [comment]
Hi all, this is not related to the iOS or device version, it's related to the Apple certificates. If for whatever reason those get updated (i.e. because of automatic provisioning or you're provisioning a new environment) you'll start hitting this issue because the app won't be correctly signed.

**Comment by MuzzledLeader2** [comment]
Same issue for me.  Just paid the apple developer account subscription only to find that I can't get past the splash screen on Hot Restart.  iPhone 5s

Keeping an eye on this thread.  Thanks.

**Comment by Siphonophora** [comment]
@MuzzledLeader2 Its not really closed, they are tracking this on the visual studio developer forum. There is a link above.

**Comment by mauroa** [comment]
Hi everyone, the issue has been fixed and will be available soon in the next VS 16.10 Preview and also in the next VS 16.9 Service Release. We've also closed the linked VS Feedback Ticket.
Thanks for your help.

**Comment by mtucker6784** [comment]
Just created my app dev account today and started playing around,  was quite frustrated but glad to see there seems to have been a resolution. Thanks for the update!

**Comment by AdamDiament** [comment]
> Hi everyone, the issue has been fixed and will be available soon in the next VS 16.10 Preview and also in the next VS 16.9 Service Release. We've also closed the linked VS Feedback Ticket.
> Thanks for your help.

Was this addressed in [16.9.2]( https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#16.9.2) - it was after this comment but I didn't see it in the release notes.

**Comment by AdamDiament** [comment]
> > Hi everyone, the issue has been fixed and will be available soon in the next VS 16.10 Preview and also in the next VS 16.9 Service Release. We've also closed the linked VS Feedback Ticket.
> > Thanks for your help.
> 
> Was this addressed in [16.9.2](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#16.9.2)? It was after this comment but I didn't see it in the release notes.

I am now running version 16.9.3. I get different behaviour but still cannot run hot restart. The build now succeed and I get a message that the app was deployed successfully. But the app icon does not appear. If I restart the phone, the app icon does appear. But launching the app by clicking on it just shows the base examining splash screen followed by a crash. If I tried debugging from visual studio after the phone restart, it shows me a message asking me to please open the manually. If I do that, I get presumably the same crash. Here are the logs, I hope it can help.

Native Crash Reporting
=================================================================
Got a segv while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================

	0x104658120 - /private/var/containers/Bundle/Application/A8867D0F-7BC8-4ACD-B497-132F235E1D8B/VisualService.iOS.app/Xamarin.PreBuilt.iOS : mono_dump_native_crash_info
	0x10464ecbc - /private/var/containers/Bundle/Application/A8867D0F-7BC8-4ACD-B497-132F235E1D8B/VisualService.iOS.app/Xamarin.PreBuilt.iOS : mono_handle_native_crash

	0x10465ba60 - /private/var/containers/Bundle/Application/A8867D0F-7BC8-4ACD-B497-132F235E1D8B/VisualService.iOS.app/Xamarin.PreBuilt.iOS : mono_sigsegv_signal_handler_debug
	0x1d9e8f298 - /usr/lib/system/libsystem_platform.dylib : <redacted>
	0x18e02ea68 - /usr/lib/system/libdyld.dylib : <redacted>
	0x18e01f83c - /usr/lib/system/libdyld.dylib : <redacted>
	0x18e02e894 - /usr/lib/system/libdyld.dylib : <redacted>
	0x18e02017c - /usr/lib/system/libdyld.dylib : <redacted>
	0x18e02f334 - /usr/lib/system/libdyld.dylib : <redacted>
	0x18e02ee1c - /usr/lib/system/libdyld.dylib : <redacted>
	0x18e030d04 - /usr/lib/system/libdyld.dylib : <redacted>
	0x18e022d34 - /usr/lib/system/libdyld.dylib : <redacted>
	0x104804970 - /private/var/containers/Bundle/Application/A8867D0F-7BC8-4ACD-B497-132F235E1D8B/VisualService.iOS.app/Xamarin.PreBuilt.iOS : do_icall

	0x1047f7eb0 - /private/var/containers/Bundle/Application/A8867D0F-7BC8-4ACD-B497-132F235E1D8B/VisualService.iOS.app/Xamarin.PreBuilt.iOS : interp_runtime_invoke
	0x10465ed3c - /private/var/containers/Bundle/Application/A8867D0F-7BC8-4ACD-B497-132F235E1D8B/VisualService.iOS.app/Xamarin.PreBuilt.iOS : mono_jit_runtime_invoke
	0x10470d2c0 - /private/var/containers/Bundle/Application/A8867D0F-7BC8-4ACD-B497-132F235E1D8B/VisualService.iOS.app/Xamarin.PreBuilt.iOS : mono_runtime_invoke_checked

	0x104712564 - /private/var/containers/Bundle/Application/A8867D0F-7BC8-4ACD-B497-132F235E1D8B/VisualService.iOS.app/Xamarin.PreBuilt.iOS : mono_runtime_exec_main_checked
	0x1046438f4 - /private/var/containers/Bundle/Application/A8867D0F-7BC8-4ACD-B497-132F235E1D8B/VisualService.iOS.app/Xamarin.PreBuilt.iOS : mono_jit_exec

	0x1047f5984 - /private/var/containers/Bundle/Application/A8867D0F-7BC8-4ACD-B497-132F235E1D8B/VisualService.iOS.app/Xamarin.PreBuilt.iOS : xamarin_main
	0x10460bc34 - /private/var/containers/Bundle/Application/A8867D0F-7BC8-4ACD-B497-132F235E1D8B/VisualService.iOS.app/Xamarin.PreBuilt.iOS : main
	0x18e01e6b0 - /usr/lib/system/libdyld.dylib : <redacted>

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x10b0e63dc):0x10b0e63cc  a5 c3 00 94 e0 03 13 aa 49 fe 02 94 20 00 20 d4  ........I... . .
0x10b0e63dc  f4 4f be a9 
	0x104803010 - /private/var/containers/Bundle/Application/A8867D0F-7BC8-4ACD-B497-132F235E1D8B/VisualService.iOS.app/Xamarin.PreBuilt.iOS : do_icall_wrapper
	0x1047f9a8c - /private/var/containers/Bundle/Application/A8867D0F-7BC8-4ACD-B497-132F235E1D8B/VisualService.iOS.app/Xamarin.PreBuilt.iOS : interp_exec_method_full

fd 7b 01 a9 fd 43 00 91 73 09 00 90  .O...{...C..s...
0x10b0e63ec  73 82 08 91 41 08 00 d0 21 04 23 91 e2 0b 04 32  s...A...!.#....2
0x10b0e63fc  e0 03 13 aa 45 c3 00 94 60 82 01 91 b0 c3 00 94  ....E...`.......

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at ObjCRuntime.Dlfcn:_dlopen <0x00026>
	  at ObjCRuntime.Dlfcn:dlopen <0x00010>
	  at Xamarin.PreBuilt.iOS.Applications:LoadFrameworks <0x0009e>
	  at Xamarin.PreBuilt.iOS.Applications:Main <0x00202>
	  at <Module>:runtime_invoke_direct_void_string[] <0x00092>
=================================================================

Thread started: <Thread Pool> #4
Thread started: <Thread Pool> #5
Thread started: <Thread Pool> #6
Thread started: <Thread Pool> #7
The app has been terminated.

**Comment by rubenribeiro123** [comment]
> > > Hi everyone, the issue has been fixed and will be available soon in the next VS 16.10 Preview and also in the next VS 16.9 Service Release. We've also closed the linked VS Feedback Ticket.
> > > Thanks for your help.
> > 
> > 
> > Was this addressed in [16.9.2](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#16.9.2)? It was after this comment but I didn't see it in the release notes.
> 
> I am now running version 16.9.3. I get different behaviour but still cannot run hot restart. The build now succeed and I get a message that the app was deployed successfully. But the app icon does not appear. If I restart the phone, the app icon does appear. But launching the app by clicking on it just shows the base examining splash screen followed by a crash. If I tried debugging from visual studio after the phone restart, it shows me a message asking me to please open the manually. If I do that, I get presumably the same crash. Here are the logs, I hope it can help.
> 
> # Native Crash Reporting
> # Got a segv while executing native code. This usually indicates
> a fatal error in the mono runtime or one of the native libraries
> used by your application.
> # =================================================================
> Native stacktrace:
> ```
> 0x104658120 - /private/var/containers/Bundle/Application/A8867D0F-7BC8-4ACD-B497-132F235E1D8B/VisualService.iOS.app/Xamarin.PreBuilt.iOS : mono_dump_native_crash_info
> 0x10464ecbc - /private/var/containers/Bundle/Application/A8867D0F-7BC8-4ACD-B497-132F235E1D8B/VisualService.iOS.app/Xamarin.PreBuilt.iOS : mono_handle_native_crash
> 
> 0x10465ba60 - /private/var/containers/Bundle/Application/A8867D0F-7BC8-4ACD-B497-132F235E1D8B/VisualService.iOS.app/Xamarin.PreBuilt.iOS : mono_sigsegv_signal_handler_debug
> 0x1d9e8f298 - /usr/lib/system/libsystem_platform.dylib : <redacted>
> 0x18e02ea68 - /usr/lib/system/libdyld.dylib : <redacted>
> 0x18e01f83c - /usr/lib/system/libdyld.dylib : <redacted>
> 0x18e02e894 - /usr/lib/system/libdyld.dylib : <redacted>
> 0x18e02017c - /usr/lib/system/libdyld.dylib : <redacted>
> 0x18e02f334 - /usr/lib/system/libdyld.dylib : <redacted>
> 0x18e02ee1c - /usr/lib/system/libdyld.dylib : <redacted>
> 0x18e030d04 - /usr/lib/system/libdyld.dylib : <redacted>
> 0x18e022d34 - /usr/lib/system/libdyld.dylib : <redacted>
> 0x104804970 - /private/var/containers/Bundle/Application/A8867D0F-7BC8-4ACD-B497-132F235E1D8B/VisualService.iOS.app/Xamarin.PreBuilt.iOS : do_icall
> 
> 0x1047f7eb0 - /private/var/containers/Bundle/Application/A8867D0F-7BC8-4ACD-B497-132F235E1D8B/VisualService.iOS.app/Xamarin.PreBuilt.iOS : interp_runtime_invoke
> 0x10465ed3c - /private/var/containers/Bundle/Application/A8867D0F-7BC8-4ACD-B497-132F235E1D8B/VisualService.iOS.app/Xamarin.PreBuilt.iOS : mono_jit_runtime_invoke
> 0x10470d2c0 - /private/var/containers/Bundle/Application/A8867D0F-7BC8-4ACD-B497-132F235E1D8B/VisualService.iOS.app/Xamarin.PreBuilt.iOS : mono_runtime_invoke_checked
> 
> 0x104712564 - /private/var/containers/Bundle/Application/A8867D0F-7BC8-4ACD-B497-132F235E1D8B/VisualService.iOS.app/Xamarin.PreBuilt.iOS : mono_runtime_exec_main_checked
> 0x1046438f4 - /private/var/containers/Bundle/Application/A8867D0F-7BC8-4ACD-B497-132F235E1D8B/VisualService.iOS.app/Xamarin.PreBuilt.iOS : mono_jit_exec
> 
> 0x1047f5984 - /private/var/containers/Bundle/Application/A8867D0F-7BC8-4ACD-B497-132F235E1D8B/VisualService.iOS.app/Xamarin.PreBuilt.iOS : xamarin_main
> 0x10460bc34 - /private/var/containers/Bundle/Application/A8867D0F-7BC8-4ACD-B497-132F235E1D8B/VisualService.iOS.app/Xamarin.PreBuilt.iOS : main
> 0x18e01e6b0 - /usr/lib/system/libdyld.dylib : <redacted>
> ```
> 
> # =================================================================
> Basic Fault Address Reporting
> Memory around native instruction pointer (0x10b0e63dc):0x10b0e63cc a5 c3 00 94 e0 03 13 aa 49 fe 02 94 20 00 20 d4 ........I... . .
> 0x10b0e63dc f4 4f be a9
> 0x104803010 - /private/var/containers/Bundle/Application/A8867D0F-7BC8-4ACD-B497-132F235E1D8B/VisualService.iOS.app/Xamarin.PreBuilt.iOS : do_icall_wrapper
> 0x1047f9a8c - /private/var/containers/Bundle/Application/A8867D0F-7BC8-4ACD-B497-132F235E1D8B/VisualService.iOS.app/Xamarin.PreBuilt.iOS : interp_exec_method_full
> 
> fd 7b 01 a9 fd 43 00 91 73 09 00 90 .O...{...C..s...
> 0x10b0e63ec 73 82 08 91 41 08 00 d0 21 04 23 91 e2 0b 04 32 s...A...!.#....2
> 0x10b0e63fc e0 03 13 aa 45 c3 00 94 60 82 01 91 b0 c3 00 94 ....E...`.......
> 
> # =================================================================
> Managed Stacktrace:
> ```
>   at <unknown> <0xffffffff>
>   at ObjCRuntime.Dlfcn:_dlopen <0x00026>
>   at ObjCRuntime.Dlfcn:dlopen <0x00010>
>   at Xamarin.PreBuilt.iOS.Applications:LoadFrameworks <0x0009e>
>   at Xamarin.PreBuilt.iOS.Applications:Main <0x00202>
>   at <Module>:runtime_invoke_direct_void_string[] <0x00092>
> ```
> 
> =================================================================
> 
> Thread started: #4
> Thread started: #5
> Thread started: #6
> Thread started: #7
> The app has been terminated.

Did you fixed this? Im getting the exact thing.

**Comment by adamzucchi** [comment]
I am running VS 2019 16.10.2 and getting the same error as @rubenribeiro123 above. @rubenribeiro123 have you found any fix/workaround?  Anyone else still hitting this?

Thanks!

**Comment by maximusfatigue** [comment]
I also have this bug

=================================================================
	Native Crash Reporting
=================================================================
Got a segv while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================

	0x1027a4120 - /private/var/containers/Bundle/Application/1B0E253D-7D5D-4A3C-9C5A-67EF4B5F8ADB/DCProParent.IOS.app/Xamarin.PreBuilt.iOS : mono_dump_native_crash_info

	0x10279acbc - /private/var/containers/Bundle/Application/1B0E253D-7D5D-4A3C-9C5A-67EF4B5F8ADB/DCProParent.IOS.app/Xamarin.PreBuilt.iOS : mono_handle_native_crash

	0x1027a7a60 - /private/var/containers/Bundle/Application/1B0E253D-7D5D-4A3C-9C5A-67EF4B5F8ADB/DCProParent.IOS.app/Xamarin.PreBuilt.iOS : mono_sigsegv_signal_handler_debug
	0x1f4bd829c - /usr/lib/system/libsystem_platform.dylib : <redacted>
	0x1a8cbb5ec - /usr/lib/system/libdyld.dylib : <redacted>

	0x1a8cab008 - /usr/lib/system/libdyld.dylib : <redacted>
	0x1a8cbb418 - /usr/lib/system/libdyld.dylib : <redacted>
	0x1a8cab948 - /usr/lib/system/libdyld.dylib : <redacted>
	0x1a8cbbf30 - /usr/lib/system/libdyld.dylib : <redacted>
	0x1a8cbb9c0 - /usr/lib/system/libdyld.dylib : <redacted>
	0x1a8cbd928 - /usr/lib/system/libdyld.dylib : <redacted>
	0x1a8caeecc - /usr/lib/system/libdyld.dylib : <redacted>

	0x102950970 - /private/var/containers/Bundle/Application/1B0E253D-7D5D-4A3C-9C5A-67EF4B5F8ADB/DCProParent.IOS.app/Xamarin.PreBuilt.iOS : do_icall

	0x10294f010 - /private/var/containers/Bundle/Application/1B0E253D-7D5D-4A3C-9C5A-67EF4B5F8ADB/DCProParent.IOS.app/Xamarin.PreBuilt.iOS : do_icall_wrapper

	0x102945a8c - /private/var/containers/Bundle/Application/1B0E253D-7D5D-4A3C-9C5A-67EF4B5F8ADB/DCProParent.IOS.app/Xamarin.PreBuilt.iOS : interp_exec_method_full
	0x102943eb0 - /private/var/containers/Bundle/Application/1B0E253D-7D5D-4A3C-9C5A-67EF4B5F8ADB/DCProParent.IOS.app/Xamarin.PreBuilt.iOS : interp_runtime_invoke
	0x1027aad3c - /private/var/containers/Bundle/Application/1B0E253D-7D5D-4A3C-9C5A-67EF4B5F8ADB/DCProParent.IOS.app/Xamarin.PreBuilt.iOS : mono_jit_runtime_invoke

	0x1028592c0 - /private/var/containers/Bundle/Application/1B0E253D-7D5D-4A3C-9C5A-67EF4B5F8ADB/DCProParent.IOS.app/Xamarin.PreBuilt.iOS : mono_runtime_invoke_checked

	0x10285e564 - /private/var/containers/Bundle/Application/1B0E253D-7D5D-4A3C-9C5A-67EF4B5F8ADB/DCProParent.IOS.app/Xamarin.PreBuilt.iOS : mono_runtime_exec_main_checked
	0x10278f8f4 - /private/var/containers/Bundle/Application/1B0E253D-7D5D-4A3C-9C5A-67EF4B5F8ADB/DCProParent.IOS.app/Xamarin.PreBuilt.iOS : mono_jit_exec

	0x102941984 - /private/var/containers/Bundle/Application/1B0E253D-7D5D-4A3C-9C5A-67EF4B5F8ADB/DCProParent.IOS.app/Xamarin.PreBuilt.iOS : xamarin_main
	0x102757c34 - /private/var/containers/Bundle/Application/1B0E253D-7D5D-4A3C-9C5A-67EF4B5F8ADB/DCProParent.IOS.app/Xamarin.PreBuilt.iOS : main
	0x1a8ca9cf8 - /usr/lib/system/libdyld.dylib : <redacted>

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x10c4f311c):0x10c4f310c  c3 bc 00 94 e0 03 13 aa 5f 00 03 94 20 00 20 d4  ........_... . .
0x10c4f311c  f4 4f be a9 fd 7b 01 a9 fd 43 00 91 73 09 00 b0  .O...{...C..s...
0x10c4f312c  73 82 2b 91 61 08 00 b0 21 38 2f 91 e0 03 13 aa  s.+.a..
.!8/.....
0x10c4f313c  02 00 ae 52 63 bc 00 94 60 82 01 91 ce bc 00 
94  ...Rc...`.......

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at ObjCRuntime.Dlfcn:_dlopen <0x00026>
	  at ObjCRuntime.Dlfcn:dlopen <0x00010>
	  at Xamarin.PreBuilt.iOS.Applications:LoadFrameworks <0x0009e>
	  at Xamarin.PreBuilt.iOS.Applications:Main <0x00202>
	  at <Module>:runtime_invoke_direct_void_string[] <0x00092>
=================================================================

**Comment by maximusfatigue** [comment]
running VS 2019 16.10.2 and latest ios

**Comment by juancardlm** [comment]
Same error here after install Xamarin.Firebase.iOS.CloudMessaging
Can not USB debug on my physical device

**Microsoft Visual Studio Community 2019 Version 16.10.2
iOS 14.6
Xamarin.Firebase.iOS.CloudMessaging 4.7.1**

```
=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at ObjCRuntime.Dlfcn:_dlopen <0x00026>
	  at ObjCRuntime.Dlfcn:dlopen <0x00010>
	  at Xamarin.PreBuilt.iOS.Applications:LoadFrameworks <0x0009e>
	  at Xamarin.PreBuilt.iOS.Applications:Main <0x00202>
	  at <Module>:runtime_invoke_direct_void_string[] <0x00092>
=================================================================
```

**Comment by maximusfatigue** [comment]
I have also recently added this package.

**Comment by adamzucchi** [comment]
My project does **not** use Xamarin.Firebase.iOS.CloudMessaging.

**Comment by echolumaque** [comment]
is there any update for this bug? currently experiencing this on iPhone 12 with iOS 14,7.1, latest version of windows 10 and vs 16.10.4. i'm using hot restart with a newly created blank project and it encounters the bug above.

**Comment by marthinch** [comment]
I also got this issue, i'm using the latest visual studio 11.1

**Comment by lukies97** [comment]
Is this the same error I reported to VS 2022?  I'm now getting this error no matter what version I use.  VS 2019 newest version, 2022 release version or even the preview. Hot Restart is completely dead for me and has been VS2022 has been released.

**Comment by dskogman** [comment]
I'm getting this same error on the latest VS2022 when deploying to an IPhone 12 but not when deploying to an IPad 6th gen.

**"The build now succeed and I get a message that the app was deployed successfully. But the app icon does not appear. If I restart the phone, the app icon does appear. But launching the app by clicking on it just shows the base examining splash screen followed by a crash."**

Any ideas/workarounds?
