### ISSUE TITLE
[Android Platform-Specific (fast scrolling)] Section Indexes are shifted

### ISSUE THREAD

**Issue by hubertdej** [xamarin/Xamarin.Forms#1481]
### Description

Problem with Section Indexes when FastScroll is enabled. They don't display properly.

### Steps to Reproduce

1. Create a blank Xamarin.Forms project named "SectionIndexing" (I used PCL).
2. Paste following code to MainPage.xaml file.
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:android="clr-namespace:Xamarin.Forms.PlatformConfiguration.AndroidSpecific;assembly=Xamarin.Forms.Core"
             x:Class="SectionIndexing.MainPage">
    <ContentPage.Content>
        <ListView x:Name="RandomStringsList"
                  IsGroupingEnabled="True"
                  GroupDisplayBinding="{Binding Key}"
                  GroupShortNameBinding="{Binding Key}"
                  android:ListView.IsFastScrollEnabled="True" >
            <ListView.ItemTemplate>
                <DataTemplate>
                    <TextCell Text="{Binding}" />
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>
    </ContentPage.Content>
</ContentPage>
```
3. Paste following code to MainPage.xaml.cs file.
```
using System;
using System.Collections.Generic;
using System.Linq;
using Xamarin.Forms;

namespace SectionIndexing
{
    public static class RandomString
    {
        private static Random random = new Random();
        public static string Generate(int length)
        {
            return new string(Enumerable.Repeat('a', length).Select(x => (char)(x + random.Next(26))).ToArray());
        }
    }

    public partial class MainPage : ContentPage
    {

        public MainPage()
        {
            InitializeComponent();

            var source = new List<string>();
            for (int count = 200; count > 0; --count)
            {
                source.Add(RandomString.Generate(10));
            }

            RandomStringsList.ItemsSource = new List<IGrouping<string, string>>(
                source.OrderBy(x => x).GroupBy(x => x[0].ToString().ToUpper()));
        }
    }
}
```

4. Deploy the project on Android device.

### Expected Behavior
Section Indexes correspond to current view.
### Actual Behavior
Section indexes are shifted by 1 for the first group, 2 for the second group, 3 for the third etc.
### Basic Information

- Version with issue(tested on): 2.4.0.280, 2.5.0.121934, 2.5.1.102606-nightly
- Last known good version: -
- IDE: Visual Studio 2017 Community
- Platform Target Frameworks:
  - Android: 8.0
- Android Support Library Version: 25.4.0.2 (for Xamarin.Forms 2.4.0.280), 26.101

- Affected Devices (tested on):
  - Samsung Galaxy S6 (6.0)
  - Samsung Galaxy S7 (7.1)

### Screenshots

<img src="https://user-images.githubusercontent.com/34969251/34462695-e57ed34c-ee49-11e7-886f-d3b807511cc0.png" width = "400"/>
<img src="https://user-images.githubusercontent.com/34969251/34462824-4262cc2e-ee4c-11e7-84ab-70d61998c419.png" width = "400"/>
<img src="https://user-images.githubusercontent.com/34969251/34462697-e5baa386-ee49-11e7-8982-e391e2c6b37c.png" width = "400"/>
<img src="https://user-images.githubusercontent.com/34969251/34462825-4281c2fa-ee4c-11e7-8b16-b5176467780f.png" width = "400"/>
<img src="https://user-images.githubusercontent.com/34969251/34462700-e5f3cefe-ee49-11e7-876f-c583e5dfd3f0.png" width = "400"/>

### Reproduction Link
https://github.com/hubertdej/SectionIndexing.git

**Comment by kingces95** [comment]
Reproduction exhibits stated actual behavior. Transition of bubble from one letter to the next occurs before all elements of previous group exit screen.

**Comment by samhouts** [comment]
@hubertdej I see that you made a fix for this issue in a fork. Have you considered contributing your fix in a PR? Thanks!

**Comment by hubertdej** [comment]
I fixed the indexing but then I noticed the scroll handle goes out of screen bounds and I gave up.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by sumascer** [comment]
I am using Xamarin 16.7.000.440, and Xamarin.Forms V4.8.0.1364 (published 8/31/2020) and I still see this issue.
