### ISSUE TITLE
[Bug] 5.0.0.2401 Introduces build error "Can't resolve the reference 'System.Void ObjCRuntime.DisposableObject::Dispose()'"

### ISSUE THREAD

**Issue by cchoupin** [xamarin/Xamarin.Forms#15280]
### Description 
Can't resolve the reference 'System.Void ObjCRuntime.DisposableObject::Dispose()', referenced from the method 'System.Void Xamarin.Forms.Platform.iOS.ContextActionsCell::.cctor()' in 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'.	Mtq.Sit.Mobile.iOS			

After updating xamarin forms, when I'm building my application (IOS) I have this error but it work well with previous versions of xamarin.forms.
It's worth mentionning that the app is using  Xamarin.Forms.Platform.iOS.WkWebViewRenderer.

### Steps to Reproduce

1. Update to xamarin.forms 5.0.0.2401 from 5.0.0.2337
2. 
3. 

### Expected Behavior
To be able to build the IOS app
### Actual Behavior
Build failure
### Basic Information

- Version with issue: 5.0.0.2401
- Last known good version: 5.0.0.2337
- Platform Target Frameworks: 
  - iOS:  15.0
- NuGet Packages: xamarin.essentials 1.7.0
- Affected Devices:  Iphone 13 pro max 

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

Microsoft Visual Studio Professional 2019
Version 16.11.11
VisualStudio.16.Release/16.11.11+32228.343
Microsoft .NET Framework
Version 4.8.04084

Version installée : Professional

Visual C++ 2019   00435-60000-00000-AA828
Microsoft Visual C++ 2019

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.11.106.23128
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.11.106.23128
Pour plus d'informations, visitez https://www.asp.net/

Assistants Microsoft Visual C++   1.0
Assistants Microsoft Visual C++

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.3000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.11.106.23128
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.3000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

Common Azure Tools   1.10
Fournit des services courants utilisables par Microsoft Azure Mobile Services et Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Extension IntelliCode   1.0
Informations détaillées sur l'extension Visual Studio IntelliCode

Extensions des outils de conteneur Visual Studio   1.0
Affichez, gérez et diagnostiquez les conteneurs dans Visual Studio.

Fabric.DiagnosticEvents   1.0
Événements de diagnostic Fabric

Gestionnaire de package NuGet   5.11.0
Gestionnaire de package NuGet dans Visual Studio. Pour plus d'informations sur NuGet, visitez https://docs.nuget.org/

Markdown Editor   1.12.253
A full featured Markdown editor with live preview and syntax highlighting. Supports GitHub flavored Markdown.

Microsoft Azure HDInsight Azure Node   2.6.3000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.3000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools pour Visual Studio   16.10
Microsoft Azure Service Fabric Tools pour Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.3000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools pour Visual Studio   2.9
Prise en charge des projets Azure Cloud Services

Microsoft Continuous Delivery Tools pour Visual Studio   0.4
Simplification de la configuration des pipelines Azure DevOps à partir de l'IDE Visual Studio.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Mono Debugging for Visual Studio   16.10.15 (552afdf)
Support for debugging Mono processes with Visual Studio.

Outils Azure App Service v3.0.0   16.11.106.23128
Outils Azure App Service v3.0.0

Outils C#   3.11.0-4.22108.8+d9bef045c4362fbcab27ef35daec4e95c8ff47e1
Composants C# utilisés dans l'IDE. Selon votre type de projet et vos paramètres, une version différente du compilateur peut être utilisée.

Outils et frameworks web ASP.NET 2012   16.11.106.23128
Pour plus d'informations, visitez https://www.asp.net/

Outils TypeScript   16.0.30526.2002
Outils TypeScript pour Microsoft Visual Studio

Outils Visual Basic   3.11.0-4.22108.8+d9bef045c4362fbcab27ef35daec4e95c8ff47e1
Composants Visual Basic utilisés dans l'IDE. Selon votre type de projet et vos paramètres, une version différente du compilateur peut être utilisée.

Package hôte de l'adaptateur de débogage de Visual Studio Code   1.0
Couche d'interopérabilité pour l'hébergement d'adaptateurs de débogage Visual Studio Code dans Visual Studio

Package Microsoft Visual Studio VC   1.0
Package Microsoft Visual Studio VC

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   16.1.0.2122504+13c05c96ea6bdbe550bd88b0bf6cdddf8cde1725
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   16.0.62201.17150
Microsoft SQL Server Data Tools

SQL Server Reporting Services   15.0.19528.0
Concepteurs Microsoft SQL Server Reporting Services
Version 15.0.19528.0

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

Visual F# Tools   16.11.0-beta.21514.6+b6c2c4f53ea3a08fa603ea93d6d2f808a62a21d1
Microsoft Visual F# Tools

Visual Studio Tools pour Conteneurs   1.0
Visual Studio Tools pour Conteneurs

Visual Studio Tools pour Docker   1.2
Développez, exécutez et validez vos applications ASP.NET Core dans l'environnement cible. Appuyez sur F5 pour exécuter votre application directement dans un conteneur avec débogage ou sur CTRL+F5 pour modifier et actualiser votre application sans avoir à recréer le conteneur.

Visual Studio Tools pour Kubernetes   1.0
Visual Studio Tools pour Kubernetes

VisualStudio.DeviceLog   1.0
Informations sur mon paquet

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.11.000.197 (d16-11@6934992)
Extension Visual Studio permettant de développer pour Xamarin.iOS et Xamarin.Android.

Xamarin Designer   16.11.0.47 (remotes/origin/d16-11@e0d612363)
Extension Visual Studio pour activer les outils Xamarin Designer dans Visual Studio.

Xamarin Templates   16.10.5 (355b57a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   12.0.0.3 (d16-11/f0e3c2d)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/d16-11@476bb5b
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.35.4@85460d3
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-11@87af37b

Xamarin.iOS and Xamarin.Mac SDK   15.2.0.17 (738fde344)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

</details>

### Build Logs

[build log.txt](https://github.com/xamarin/Xamarin.Forms/files/8399289/build.log.txt)

**Comment by GeoSaffer** [comment]
I have the same issue

I have found that in the iOS Build tab set Linker behavior to **dont link** 
  - this will allow you to build and run on your device
  - This WILL FAIL when uploading to TestFlight
  -

As soon as I change it to **Link Framework SDK's only** or **Link all**, I get the same error.

at this point I am stuck and can not get any of my iOS ups updated.

**Comment by jfversluis** [comment]
You might want to check if you installed the new (or at least the same) version on all of your projects: iOS, shared, Android and others if you have more platforms. Then do some aggressive cleaning and rebuilding of the project

**Comment by GnanaPriyaNamasivayam** [comment]
I'm also facing same issue in my iOS project. I could even build the application after updating Xamarin Forms 5.0.0.2337 to 5.0.0.2401.
Cleaning and rebuilding the application doesn't help in my application. Still same error occurs. 
I didn't face this issue in 5.0.0.2291, 5.0.0.2337.

**Comment by Alex-Covecube** [comment]
Same exact issue here that started after updating. I found this issue after googling the error message. Looks like 5.0.0.2401 is broken.

**Comment by sisaacks** [comment]
Yup same exact issue for me too.....I updated to 5.0.0.2401 and now I am getting that error.  If I revert back to 5.0.0.2337 the error goes away.  I reverted back to 5.0.0.2401 and I changed the Linker on the IOS project to "Dont Link" then built and the build was successful.  If I remember correctly this was an issue that happened before.  I think Xmarin is getting ready to push out another version to fix the Android Splash screen issue....hopefully they will fix this too....because changing the linker is not ideal

**Comment by sisaacks** [comment]
> Same exact issue here that started after updating. I found this thread after googling the error message. Looks like 5.0.0.2401 is broken.

Check out what I wrote above....it will at least get the project to build until this is fixed

**Comment by vgad03** [comment]
So currently we can only get a successful build but fail on testflight if we set the linker to Dont Link? Anyone know when the update will be?

**Comment by sisaacks** [comment]
@vgad03 I would roll back to 5.0.0.2337 if you're trying to publish out to TestFlight.  Switching the Linker is just a way to get the project to build.  I should have mentioned above that you can't send to Testflight.....at least I dont know a way.

**Comment by sisaacks** [comment]
@jfversluis any idea when this might be fixed?  For now we can roll back...unless there is a new version to fix the Android Splash Screen that does not include this fix.

**Comment by vgad03** [comment]
@sisaacks Thanks for that. I think rolling back to 5.0.0.2337 would be the best way to go for now untill there is a fix. I am a bit new to Xamarin, how do we go about rolling back the version?

Thanks.

**Comment by sisaacks** [comment]
I am  using windows, I am not sure on MAC, but windows you right click on the project and open the Nuget Package Manager.  Search for Xamarin Forms, Uninstall the current version and select the previous version to install

**Comment by vgad03** [comment]
Amazing im on windows too! I'll do that now. Thanks a lot

**Comment by vgad03** [comment]
@sisaacks No luck...i get more errors when i roll back to 5.0.0.2337...see screenshot attache
<img width="523" alt="errormessage" src="https://user-images.githubusercontent.com/87885359/161683253-4f095155-e72a-48d9-85b7-0ef877a7c938.png">
d

**Comment by sisaacks** [comment]
@vgad03 Did you clear out our big and obj files in the shared project and ios project, clean, rebuild?  Did you look at your main project under the Dependency folder at Packages, to make sure your current Xamarin Forms is the 5.0.0.2337

**Comment by vgad03** [comment]
@sisaacks yep did all that. Made sure to clean out shared and iOS projects bin and obj folders. Made sure under dependencies its the correct Xamarin Forms version that we want which is 5.0.0.2337. And yes i uninstalled xamarin forms from all projects and reinstalled the correct version. 

All the errors are happening on the iOS project. Same as above image attached.

**Comment by sisaacks** [comment]
@vgad03 The only thing I can think to do is create a new blank project, and then compare the IOS settings to your settings.  I had an issue for MONTHS where the AppIcon was missing according to Transporter.  I found out the issue by creating a new project and talking with a Microsoft guy on a form.  Duplicate file was the issue.    

I would check all the IOS settings and then compare the project config files and see if there is any difference.

**Comment by vgad03** [comment]
@sisaacks yea that was my next problem solving step lol. Will do thanks a lot :)

**Comment by vgad03** [comment]
@sisaacks yea its a bit annoying when you are waiting on realease a fix...

No i have seen that issue. 

I cant seem to even roll back and get it to compile atm so im stuck :(

**Comment by sisaacks** [comment]
@vgad03 the only other thing you could do, your project is not huge, is transfer everything over to a new project and add that one in then delete your old one

**Comment by vgad03** [comment]
mmm i could...is there no eta on the new xamarin realease?

**Comment by sisaacks** [comment]
> mmm i could...is there no eta on the new xamarin release?

I would not know.  @jfversluis may know...I would assume within in the next week or so

**Comment by vgad03** [comment]
@sisaacks well i managed to successfully rebuild with the latest version of xamarin 5.0.0.2401. However archiving is throwing the 'System.Void ObjCRuntime.DisposableObject::Dispose()' error now.

**Comment by sisaacks** [comment]
Yeah thats the error I get just building Xamarin with that version.  Thats the error I believe all the people are getting above as well.  I am not sure how you built and didnt get that error.

**Comment by vgad03** [comment]
> Yeah thats the error I get just building Xamarin with that version. Thats the error I believe all the people are getting above as well. I am not sure how you built and didnt get that error.

Yea not too sure either but it built after a clean and this is with the linker set to 'Link Framework SDKs only' 

But then it wont archive...

**Comment by sisaacks** [comment]
> > Yeah thats the error I get just building Xamarin with that version. Thats the error I believe all the people are getting above as well. I am not sure how you built and didnt get that error.
> 
> Yea not too sure either but it built after a clean and this is with the linker set to 'Link Framework SDKs only'
> 
> But then it wont archive...

Well you can at least develop and build now....but being you can build...maybe try rolling back to the previous version now.  Sounds like errors you were getting have gone away.  I would bet if you roll back it will work now

**Comment by vgad03** [comment]
@sisaacks  Yea doing that now and will let you know

**Comment by vgad03** [comment]
@sisaacks same bunch of errors when i revert back...but when i am on latest version of xamarin.forms i can clean and build successfully

**Comment by sisaacks** [comment]
@xamarin-release-manager  Do we have an ETA on this issue?  Is anyone looking into it?

**Comment by vgad03** [comment]
> @vgad03  Weird.....I have no errors on the previous version but get the error everyone else does on the current.  Hopefully this gets fixed soon.  
> 
> So create a new project with the previous version and see if you can build.  IF you can maybe transfer everything over.  

Yea I'll give that a shot today and see if I can build on a new project.

**Comment by jfversluis** [comment]
Hey everyone, thanks for all the info and collaboration here! We're looking into it. While doing so and trying to rule out some things I'd like your help. 

1. To rule out a change in our build system, could you get the resulting package from [this PR](https://github.com/xamarin/Xamarin.Forms/pull/15289) here as per [the instructions here](https://github.com/xamarin/Xamarin.Forms/wiki/Preview-Packages#pull-requests-). Make sure to get the exact version as listed on the PR. To be clear: I do not recommend using this package moving forward as it contains functionality that has not been merged yet. This is only to be used to rule out a possible cause of the initial issue.

(more tbd)

**Comment by jfversluis** [comment]
I have made some inquiries internally and it would seem that probably the latest version of Forms is compiled against the latest version of Xamarin.iOS which introduced this new `DisposableObject::Dispose` APIs. It would appear that the people having issues with this are not using the latest Xamarin.iOS version. Could you see if there are any updates for Visual Studio, install those and see if that resolves the issue?

**Comment by sisaacks** [comment]
@jfversluis I am developing on Windows and have a MAC as a build server.  I updated the Visual Studio on MAC.  I then connected to the MAC from windows, and I received a warning that there is a IOS.Xamarin mismatch.  I declined to down grade the MAC.  After connecting to the MAC I rebuilt and the error was not longer there.

**Comment by rmarinho** [comment]
Anyone having this issue, can confirm if you update stable channel you still see this error?

**Comment by vgad03** [comment]
I have updated my Xamarin.iOS SDK version to 15.8.0.0 on my MAC but i its not compatible with the latest version of Visual Studio on my windows machine. Checking for updates says its up to date. And then when i try to pair to my MAC i get a mismatch error for Xamarin.iOS sdks. See image attached...
![image](https://user-images.githubusercontent.com/87885359/162336923-61fa989e-3c93-49c1-9e3c-f33df25ed388.png)

**Comment by sisaacks** [comment]
> I have updated my Xamarin.iOS SDK version to 15.8.0.0 on my MAC but i its not compatible with the latest version of Visual Studio on my windows machine. Checking for updates says its up to date. And then when i try to pair to my MAC i get a mismatch error for Xamarin.iOS sdks. See image attached... ![image](https://user-images.githubusercontent.com/87885359/162336923-61fa989e-3c93-49c1-9e3c-f33df25ed388.png)

Jus hit OK and conitinue......it will work.

**Comment by vgad03** [comment]
no good still for me :( getting the following error...have got latest version of xamarin.forms and updated to latest xamarin.iOS on my mac
<img width="540" alt="SCREENSHOT" src="https://user-images.githubusercontent.com/87885359/162356203-e3c37600-f62d-4dbe-9121-74ca180873fd.png">

**Comment by sisaacks** [comment]
> no good still for me :( getting the following error...have got latest version of xamarin.forms and updated to latest xamarin.iOS on my mac <img alt="SCREENSHOT" width="540" src="https://user-images.githubusercontent.com/87885359/162356203-e3c37600-f62d-4dbe-9121-74ca180873fd.png">

what is giving you that error?  Transporter?  Why are you trying to archive an IOS project?  If you're trying to get your app to the app store....use Transporter to send your app to TestFlight.  

1.  Make sure you linker is set correctly "Link SDK's only"
2.  Delete all Bin/Obj's in each project and rebuild
3.  If you're using Transporter make sure its up to date

**Comment by vgad03** [comment]
@sisaacks I am archiving the Xamarin.iOS project on Visual Studio (Windows). When i get the archive i use Transporter on my mac to upload it to the App Store. So at the moment i dont even have an archive to feed to Transporter. 

ill have a look at option 4 and see if i need to delete anything on my MAC

**Comment by sisaacks** [comment]
> @sisaacks I am archiving the Xamarin.iOS project on Visual Studio (Windows). When i get the archive i use Transporter on my mac to upload it to the App Store. So at the moment i dont even have an archive to feed to Transporter.
> 
> ill have a look at option 4 and see if i need to delete anything on my MAC

@vgad03 what version of VS are you using?  In 2019 all I did was build the IOS in release mode.  Right click on the IOS project and select "Show IPA on Build Server".  Then on the MAC the IPA would show up, then drag it into transporter

**Comment by vgad03** [comment]
@sisaacks i didnt know you could do that...did that and it says its been sent to the build server but i cant find the IPA file anywhere in that ~/Library/Caches/Xamarin/(MY PROJECT)

**Comment by sisaacks** [comment]
@vgad03 when you click on "Show IPA file on build server" it should how up in a popup with other files and it will be highlighted

**Comment by vgad03** [comment]
@sisaacks i just get the 
![image](https://user-images.githubusercontent.com/87885359/162648005-4a5d34a6-52c9-4214-911d-3d5133364326.png)

but nothing that indicates where it has been stored

**Comment by sisaacks** [comment]
@vgad03 I dont understand what you're asking.  When you right click in the solution explorer....on the windows box and say "Show IPA on build server" it should show in a popup on the MAC and already be highlighted.  IF its not doing that, then you have something wrong.

**Comment by vgad03** [comment]
@sisaacks oh its not doing that at all...something is wrong

**Comment by sisaacks** [comment]
@vgad03 are you testing on an actual IOS device?  I mean do you have a phone plugged into the MAC?  
The link above I Sent you Finder -> Go -> Go To Folder then type ~/Library/Caches/Xamarin/
did you check there to see if there is a build?  
Also you may disconnect and reconnect to the MAC server...clean and build

**Comment by vgad03** [comment]
@sisaacks nope not testing on actual iOS device. I want the IPA file so i can feed it to transporter and get it on TestFlight
I do have a build in that path just no IPA file

Where do I look in that folder for the IPA file?

I did disconnect and reconnect and did a clean and build but nothing pops up when i click show IPA on build server

**Comment by sisaacks** [comment]
> @sisaacks nope not testing on actual iOS device. I want the IPA file so i can feed it to transporter and get it on TestFlight I do have a build in that path just no IPA file
> 
> Where do I look in that folder for the IPA file?
> 
> I did disconnect and reconnect and did a clean and build but nothing pops up when i click show IPA on build server

@vgad03 as mentioned above, on your windows device, if you right click on the solution and select "Show IPA on Build server" a folder should open on the MAC containing multiple files including the IPA.  IF its not then you have done something wrong.  I have an IOS device connected to my MAC and I select that device in VS for a build option.  If you are using a simulator, it should not matter, you should still see the IPA doing what I have told you.  If you do not...then you have something set up wrong.  I do this every time I want to put the IPA into Transporter.  

https://stackoverflow.com/questions/62151691/where-is-the-ipa-on-the-mac-when-its-used-as-a-build-server

**Comment by vgad03** [comment]
@sisaacks alright thanks for that...ill take a look at my setup and see if ive done something wrong...thanks so much

**Comment by sisaacks** [comment]
> @sisaacks alright thanks for that...ill take a look at my setup and see if ive done something wrong...thanks so much

@vgad03 In your Xamarin IOS project...right click on the project and select properties.  Under iOS IPA Optoins do you have the "Build iTunes Package Archive (IPA) checkbox checked?  If not, probably why you're not seeing the IPA on the MAC

**Comment by vgad03** [comment]
> > @sisaacks alright thanks for that...ill take a look at my setup and see if ive done something wrong...thanks so much
> 
> @vgad03 In your Xamarin IOS project...right click on the project and select properties. Under iOS IPA Optoins do you have the "Build iTunes Package Archive (IPA) checkbox checked? If not, probably why you're not seeing the IPA on the MAC

yes i have it checked

**Comment by sisaacks** [comment]
> > > @sisaacks alright thanks for that...ill take a look at my setup and see if ive done something wrong...thanks so much
> > 
> > 
> > @vgad03 In your Xamarin IOS project...right click on the project and select properties. Under iOS IPA Optoins do you have the "Build iTunes Package Archive (IPA) checkbox checked? If not, probably why you're not seeing the IPA on the MAC
> 
> yes i have it checked

Then I am not sure.  It sounds like there is an issue with the connection to your MAC.  If you are not seeing any build files on the MAC by doing the following:  Finder -> Go -> Go To Folder then type ~/Library/Caches/Xamarin/
then the project is not being built on your MAC and something is wrong with the pair to windows

**Comment by vgad03** [comment]
@sisaacks im starting to get the original build errors that we originally had even though im on latest xamarin.ios and xamarin.forms versions...hence i cant get the IPA because my builds are failing

**Comment by sisaacks** [comment]
> @sisaacks im starting to get the original build errors that we originally had even though im on latest xamarin.ios and xamarin.forms versions...hence i cant get the IPA because my builds are failing

Make sure the Xamarin on the MAC has not been overwritten with a lower version when connecting.  Thats the only thing I would know to check.  Unless your fiddling with settings you shouldn't be getting errors.  

One thing you could do, create a new project, build, and see if you have the issues.  Right click on the IOS and select Show IPA on build server.  See if it works.

**Comment by luismts** [comment]
I'm having the same issue. Any workaround guys?

cc @jfversluis

**Comment by sisaacks** [comment]
> I'm having the same issue. In my case, I'm working with App Center.
> 
> Any workaround guys?
> 
> cc @jfversluis

What do you mean you're having the same issue but working with the app center?  Meaning your trying to upload to the app center and not test flight?  If you're having issue make sure that you're MAC is running the correct version of VS.  I have not tried since this, but @jfversluis mentioned above to make sure when connecting to the MAC hit CANCEL when asking to upgrade visual studio on the MAC.  I posted this above: 

I have updated my Xamarin.iOS SDK version to 15.8.0.0 on my MAC but i its not compatible with the latest version of Visual Studio on my windows machine. Checking for updates says its up to date. And then when i try to pair to my MAC i get a mismatch error for Xamarin.iOS sdks. See image attached... image

Jus hit OK and conitinue......it will work. Dont overwrite....decline to overwrite and continue connecting. It will all be ok.

**Comment by luismts** [comment]
I fixed it.

I used the latest SDK on App Center and It's working.
![image](https://user-images.githubusercontent.com/20643876/165156422-9e71fd3c-a1fc-4a13-8d6e-8b2919545ff7.png)

Thanks @jfversluis

**Comment by luismts** [comment]
> > I'm having the same issue. In my case, I'm working with App Center.
> > Any workaround guys?
> > cc @jfversluis
> 
> What do you mean you're having the same issue but working with the app center? Meaning your trying to upload to the app center and not test flight? If you're having issue make sure that you're MAC is running the correct version of VS. I have not tried since this, but @jfversluis mentioned above to make sure when connecting to the MAC hit CANCEL when asking to upgrade visual studio on the MAC. I posted this above:
> 
> I have updated my Xamarin.iOS SDK version to 15.8.0.0 on my MAC but i its not compatible with the latest version of Visual Studio on my windows machine. Checking for updates says its up to date. And then when i try to pair to my MAC i get a mismatch error for Xamarin.iOS sdks. See image attached... image
> 
> Jus hit OK and conitinue......it will work. Dont overwrite....decline to overwrite and continue connecting. It will all be ok.

Was not compiling on App Center.

**Comment by jfversluis** [comment]
I think the fix for this one is clear. Make sure that you compile with iOS 15.4 and up. You can select that on App Center when building and if you're using it locally make sure that your Windows and Mac build host Xamarin.iOS versions match. Closing this for now!

**Comment by ramtechjoe** [comment]
Really frustrating that the most current versions of 2019 don't update to the newer versions of Xamarin.iOS.  There are reasons one might need to continue using 2019 and not want to migrate to 2022

**Comment by PatrickRyder** [comment]
> > Same exact issue here that started after updating. I found this thread after googling the error message. Looks like 5.0.0.2401 is broken.
> 
> Check out what I wrote above....it will at least get the project to build until this is fixed

My linker was already set to 'Don't link' and I still get this error. But to be clear, mine is not a build error; it is a runtime exception. The code was running fine before updating to 2401.

**Comment by PatrickRyder** [comment]
I too am seeing this as a runtime exception in previously stable code.
