### ISSUE TITLE
[Android] Xamarin: Cannot access a disposed object.

### ISSUE THREAD

**Issue by rodrigodemoraes97** [xamarin/Xamarin.Forms#2406]
Hi everybody. I am having a problem in my production app that is the exception below. The problem makes the app stops, but I've never reproduced it in my development environment. Some ideias of how I could solve it? I read it could be some xamarin issue, but I really need some way to correct this.

Any help would be apreciated. Thanks folks!

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Android.Widget.EditText'.
  at Java.Interop.JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self) [0x00029] in <c7147c8e4d504ca89af706ea53f4f899>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00000] in <c7147c8e4d504ca89af706ea53f4f899>:0 
  at Android.Widget.TextView.set_HintFormatted (Java.Lang.ICharSequence value) [0x00029] in <647c078395d84ac6b2c54c126f4053aa>:0 
  at Android.Widget.TextView.set_Hint (System.String value) [0x0000d] in <647c078395d84ac6b2c54c126f4053aa>:0 
  at Xamarin.Forms.Platform.Android.AppCompat.PickerRenderer.UpdatePicker () [0x00011] in <173f39d71f0d4d928f5bbea42e96ffa8>:0 
  at Xamarin.Forms.Platform.Android.AppCompat.PickerRenderer.RowsCollectionChanged (System.Object sender, System.EventArgs e) [0x00000] in <173f39d71f0d4d928f5bbea42e96ffa8>:0 
  at (wrapper delegate-invoke) <Module>.invoke_void_object_NotifyCollectionChangedEventArgs(object,System.Collections.Specialized.NotifyCollectionChangedEventArgs)
  at System.Collections.ObjectModel.ObservableCollection`1[T].OnCollectionChanged (System.Collections.Specialized.NotifyCollectionChangedEventArgs e) [0x0000f] in <dd651d2aa93c4ff3aaf40cce39f149a0>:0 
  at System.Collections.ObjectModel.ObservableCollection`1[T].OnCollectionReset () [0x00007] in <dd651d2aa93c4ff3aaf40cce39f149a0>:0 
  at System.Collections.ObjectModel.ObservableCollection`1[T].ClearItems () [0x00022] in <dd651d2aa93c4ff3aaf40cce39f149a0>:0 
  at System.Collections.ObjectModel.Collection`1[T].Clear () [0x00014] in <70a144a154bc415d9cac66f523403cea>:0 
  at Xamarin.Forms.Internals.LockableObservableListWrapper.InternalClear () [0x00000] in <3754ae802c714b298131b9c985b370ad>:0 
  at Xamarin.Forms.Picker.OnItemsSourceChanged (System.Collections.IList oldValue, System.Collections.IList newValue) [0x00059] in <3754ae802c714b298131b9c985b370ad>:0 
  at Xamarin.Forms.Picker.OnItemsSourceChanged (Xamarin.Forms.BindableObject bindable, System.Object oldValue, System.Object newValue) [0x00000] in <3754ae802c714b298131b9c985b370ad>:0 
  at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) [0x00121] in <3754ae802c714b298131b9c985b370ad>:0 
  at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x0015b] in <3754ae802c714b298131b9c985b370ad>:0 
  at Xamarin.Forms.BindingExpression.ApplyCore (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property, System.Boolean fromTarget) [0x001f9] in <3754ae802c714b298131b9c985b370ad>:0 
  at Xamarin.Forms.BindingExpression.Apply (System.Boolean fromTarget) [0x0003e] in <3754ae802c714b298131b9c985b370ad>:0 
  at Xamarin.Forms.BindingExpression+BindingExpressionPart.<PropertyChanged>b__47_0 () [0x00000] in <3754ae802c714b298131b9c985b370ad>:0 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <647c078395d84ac6b2c54c126f4053aa>:0 
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <647c078395d84ac6b2c54c126f4053aa>:0 
  at (wrapper dynamic-method) System.Object.78f195ca-4d88-4d09-bf84-9711161b08ce(intptr,intptr)

**Comment by rmarinho** [comment]
Hi @rodrigodemoraes97 we will need more information, like versions of Xamarin.Forms you are using and a reproduction test case. Could be a issue fixed in recent versions.

**Comment by Magendanz** [comment]
I'm seeing this too on Xamarin.Forms v2.5.0.280555.  Seems to have started when I introduced CarouselView by alexrainman.  I didn't see the problem with CarouselPage, but needed to switch to CarouselView for virtualization.

**Comment by jassmith** [comment]
Looks to me that CarouselView likely has some issue with how it recycles views :/ Something isn't getting unhooked right.

**Comment by deepesh002** [comment]
This issue is not specific to carousel view. This also happens when we have list views on different pages with custom view cells and navigate to and fro between them. 

Note:- All listviews are marked with caching strategy "Recycle Element".

**Comment by hartez** [comment]
Moving this to `needs-info` while we wait for confirmation from @Magendanz that this still happens in the feature-carouselview branch.

**Comment by hartez** [comment]
> This issue is not specific to carousel view.

`ObjectDisposedException` is a type of exception which can happen in many places for many different reasons; it's a lot like a `NullReferenceException`. So the odds are good that all three of the reports in this issue are actually separate instances of this exception, each requiring its own fix.

@Magendanz - could you please open an issue about `ObjectDisposedException` and CarouselView, and include any information you can give us on how you're using CarouselView and when the exception occurs?

@deepesh002 - it sounds like you're running into this with ListViews; could you please open an issue about `ObjectDisposedException` and ListView and include any information you can give us on how you're using ListView and when the exception occurs?

@rodrigodemoraes97 - Your problem appears to be with the Picker - how are you using it, and what version of Forms are you using?

**Comment by AndreiMisiukevich** [comment]
@Magendanz I suggest you to try my plugin for implementing carouselView until this issue will be fixed.

It supports caching and much more customizable.

https://github.com/AndreiMisiukevich/CardView

**Comment by deepesh002** [comment]
#2793 created as suggested

**Comment by PureWeen** [comment]
I created a central issue for this type of exception
https://github.com/xamarin/Xamarin.Forms/issues/2829

And I'm going to close this one for now
If you don't feel like the issue I created represents the problem here just let me know and we can reopen

**Comment by DeepikaBalaSubramaniyan** [comment]
Hi @PureWeen , @deepesh002 , @yustanj 

Same issue has replicated in our custom control too, while tried to reuse the Entry view which was stored in bin by using Enqueue and Dequeue process of type Queue<WeakReference>. 

While edit the entry view from Queue<WeakReference> bin, Entry.Focus() method does not show the keyboard, also while calls a Entry.Unfocus() method I am getting can not access a disposed object exception , object name Xaamrin.forms.platform.android.FormsEditText ,
Attached the exception screen shot: 
![image](https://user-images.githubusercontent.com/42173947/53681866-85ce2d00-3d15-11e9-9dc3-0f0d0cca7e89.png)

And issue was only in xamarin forms version 3.5, At 3.4 last stable version our control working fine.
I tried your solution in my  custom renderer, Which was not working, Is it frame work bug? If any one was facing the same issue provide your possible solutions. Thanks in advance.

**Comment by PureWeen** [comment]
@DeepikaBalaSubramaniyan 

https://github.com/xamarin/Xamarin.Forms/issues/5238

**Comment by DeepikaBalaSubramaniyan** [comment]
Hi @PureWeen 

Thanks for your reply, I understand this issue will get fixed in xamarin forms 3.6 stable version.

**Comment by DeepikaBalaSubramaniyan** [comment]
Hi @PureWeen 

Still I am facing the same issue in latest stable version 3.6 too,

At Xamarin forms version 3.6 latest stable, After enabling the Exception setting(C++ Extensions, Common Language Runtime Exceptions), same object disposed exception of entry view was thrown while calling entry.UnFocus() method

I have attached the screen shot for this issue

image

Forms version nuget for your reference

image

Can you look in to this and include the fix with upcoming nuget?

**Comment by batilak** [comment]
Even I am facing ObjectDisposed crash on Android for TextCellView in List with Xamarin Forms 3.6.0.344457.

**Comment by PureWeen** [comment]
@batilak can you try a newer version of Forms and see if you have the same issue? If so can you create a new issue with a sample project please?
