### ISSUE TITLE
Xamarin scrollview overlaps other content when scrolling

### ISSUE THREAD

**Issue by SaskiaL** [xamarin/Xamarin.Forms#3535]
I have a xamarin forms app. The app has a page with a stacklayout. The stacklayout contains a grid with some labels and a edit box on the top.
Under that the stacklayout has a scrollview with several grids.

Since the latest update from xamarin the scrollviews overlaps the grid with controls on the top of the page. The scrolling area reaches up to the toolbar.

I have only tested on android. 

This is what it looks like:
![scrolloverothercontent1](https://user-images.githubusercontent.com/20900758/43940834-c28ea944-9c71-11e8-9190-3c3a7c7cc4e4.png)

This is what is was before the last update:
![scrollasitshouldbe1](https://user-images.githubusercontent.com/20900758/43940840-ca7e369c-9c71-11e8-99d0-43581facc723.png)

Xamarin: 4.10.10.2
Xamarin android: 8.3.3.2

**Comment by samhouts** [comment]
Can you specify which version was working and which version you updated to? Thanks!

**Comment by samhouts** [comment]
Also, if you could attach a small reproduction project, that would be helpful! Thanks

**Comment by SaskiaL** [comment]
It seems that the problem is solved. No idea how. If it happens again, I will try to create a small project showing the problem.

Thanks, Saskia

**Comment by samhouts** [comment]
Thank you!

**Comment by titoleru** [comment]
This issue should be reopened. I am having the same problem as of September 2019. As shown in https://forums.xamarin.com/discussion/20945/scrollview-in-xaml/p2 , I am not the only one...

**Comment by motasemloubani91** [comment]
This should be reopened. I still have this issue all latest versions of xamarin forms !!!!! what the hell is that, this is a very basic control !!! not a complex one and has this bug from the first version of xamarin !!! this reduce my team productivity and delivery !!!

**Comment by motasemloubani91** [comment]
we are now stopped and cann't push the next version of the app to the store because of this !!!!
