### ISSUE TITLE
ChangeCanExecute does not trigger the appropriate method under certain circumstances

### ISSUE THREAD

**Issue by EP01** [xamarin/Xamarin.Forms#4444]
### Description

I have an issue after updating to `3.4.0.1008975` from `3.3.0.967583`.

Under certain circumstances (yet to be determined) calling `((Command) MyCommand).ChangeCanExecute();` does not trigger the `MyCommandCanExecute` logic that it's tied to. This happens every time reliably with the latest version, the previous version works fine.

### Steps to Reproduce

We have a fairly complex application. I have tried (and failed so far) to reproduce the issue in a blank Xamarin.Forms app. I'll try to give you an idea of what my setup is: it's a ListView which the user can select multiple items from before clicking Next. When an item is tapped, `ItemClickExecute` is triggered which changes the item to "selected" so that a tick appears next to it. It then calls `((Command) MyCommand).ChangeCanExecute();` which does not hit the `MyCommandCanExecute` method. The `MyCommandCanExecute` method contains some validation to check whether the Next button should be enabled or disabled if an item is selected or not. I'll include a screenshot of the immediate code I'm referring to.

### Expected Behavior

The method is triggered when `ChangeCanExecute` is called.

### Actual Behavior

The method is not triggered when `ChangeCanExecute` is called.

### Basic Information

- Version with issue: 3.4.0.1008975
- Last known good version: 3.3.0.967583
- IDE: Visual Studio 2017 15.9.0
- Platform Target Frameworks: 
  - Android: 9.0 
  - UWP:  17763

### Screenshots

![canexecute_bug](https://user-images.githubusercontent.com/22454118/48623368-58958300-e9a1-11e8-8a60-a0e63d0d8f38.png)
![canexecute_bug1](https://user-images.githubusercontent.com/22454118/48623369-58958300-e9a1-11e8-8297-0647aee03c61.png)

**Comment by kingces95** [comment]
Hm, we'd need a smaller reproduction to track this down. Short of that, you could try using `.create-nuget.bat` to build your own nuget package for more easy debugging. If you could generate some stack traces that might point us in the right direction. You may also be able to bisect the failure. If you can identify the PR then we'd prob be able to figure out what's changed.

**Comment by EP01** [comment]
@kingces95 I've just spent a few more hours trying to reproduce this issue in a blank Xamarin.Forms app and I'm getting nowhere. I can't seem to work out what the unique factor in our app that is causing this is, compared to the template. Could we arrange a debugging session or something? For someone to take a closer look at the code.

**Comment by EP01** [comment]
If I had to guess I would say it's related to #3852, going to build a nuget package from the previous commit to confirm.

**Comment by samhouts** [comment]
@hartez What do you think about this? Without a reproduction project, my instinct is telling me that the commands are now being collected as the ViewCells are recycled, but I am not sure if this is a good thing or a bad thing.

**Comment by hartez** [comment]
@EP01 Is there any chance you're using ListViewCachingStrategy="RecycleElement" in your application?

**Comment by hartez** [comment]
@EP01 Also, in the screenshot you provided - where does `NextCmd` come from?

**Comment by EP01** [comment]
@hartez 
Yes I use `ListViewCachingStrategy="RecycleElementAndDataTemplate"` in all but one ListView in my app, including this one, for the performance improvements on Android. The exception is one where I use just `"RecycleElement"` due to using multiple DataTemplates in that one. I was under the impression this should have no (intended) effect on UWP.

As for the second question, `NextCmd` is an `ICommand` bound to the XAML view. For example, `<Button Command="{Binding NextCmd}">`.

**Comment by kingces95** [comment]
@EP01 We're committed to helping you fix this but we'll need a reproduction, or short of that, some logging information. Please attach your reduced reproductions that you believe should reproduce the issue even if they do not. That way we can collaborate on where we might put logging statements that you could run your full reproduction against.  To help gather the logs I've fixed the `.create-nuget.bat` script so you can get better stack traces etc. https://github.com/xamarin/Xamarin.Forms/pull/4668. No need to wait for the PR to go in -- you can just check it out and use it. See if you can't add some logging in a branch. Then we can come back and add some. Eventually, we'll figure out what's going on..

**Comment by EP01** [comment]
@kingces95 @hartez @samhouts 
I am still having issues creating a repro of this issue. Recently one of our libraries has started requiring Forms 3.4, so losing support from them makes this a higher priority issue for us. I have brought 2 additional members of my team on board to try to create a repro.

In the meantime, would it be possible to arrange a debugging session with one of your team members to track this issue down?

**Comment by samhouts** [comment]
@EP01 We typically use live debugging sessions as a last resort. It's far more efficient to give us a code sample that we can bring into our environments and adjust until we can get the issue to reproduce. If you do not want to post your code publicly, you can opt to send it to us via email. Does that work for you? Thanks!

**Comment by EP01** [comment]
@samhouts 
We have managed to work around the issue by refactoring the code in our button control to use `VisualStateManager`. We still don't know why the problem occured in the first place; the code worked just fine with 3.3. I can send you a copy of the problematic code if you still want to investigate internally, otherwise feel free to close this.

**Comment by samhouts** [comment]
@EP01 Great to hear you got it working! I don't want to ignore a potential regression, though. Please do send me the code (sahou at Microsoft), and I'll take a look. Thank you!

**Comment by MagicAndre1981** [comment]
> We have managed to work around the issue by refactoring the code in our button control to use `VisualStateManager`. 

this is what I also did. Thanks for the tip 👍

**Comment by samhouts** [comment]
@MagicAndre1981 By any chance, were you able to narrow down the factors that contributed to you experiencing this issue? Thanks!

**Comment by MagicAndre1981** [comment]
I now use VisualStateManager . Ask @EP01 for code, he has a repro

**Comment by samhouts** [comment]
@MagicAndre1981 Thanks! I have the code from @EP01 , but I was unfortunately unable to reproduce the problem from it.

**Comment by MagicAndre1981** [comment]
I did not commit the not working code, after finding this issue here I replaced it with VisualStateManager

**Comment by samhouts** [comment]
Fair enough! I'm going to go ahead and close this issue, and hopefully we'll get a report that will allow us to track down the cause. Thanks!!

**Comment by MagicAndre1981** [comment]
@samhouts 

I use VS2017 and at time of opening this item, current version was VS2017. Maybe you use VS2019 and here it doesn't trigger?
