### ISSUE TITLE
CollectionView item hidden holds space

### ISSUE THREAD

**Issue by psp589** [xamarin/Xamarin.Forms#5647]
### Description
When a Item gets hidden it doesn't free its space and It is still seleccionable.
### Steps to Reproduce
Having this XAML
```
<ContentPage>
        <Grid VerticalOptions="Center"
              HorizontalOptions="Center">
            <StackLayout Orientation="Horizontal">
                <CollectionView WidthRequest="400" SelectionMode="Single" HorizontalOptions="Center" ItemsSource="{Binding ObservableCollectionTest}" BackgroundColor="Green">
                    <CollectionView.ItemTemplate>
                        <DataTemplate>
                            <Grid RowSpacing="0"
                                  ColumnSpacing="0"
                                  Padding="0"
                                  Margin="0"
                                  HeightRequest="{Binding IsVisible,Converter={StaticResource BoolToHeight},Mode=OneWay, ConverterParameter=-1}"
                                  IsVisible="{Binding IsVisible}"
                                  BackgroundColor="Yellow">
                                <Label IsVisible="{Binding IsVisible}"
                                       Text="{Binding Text}" />
                            </Grid>
                        </DataTemplate>
                    </CollectionView.ItemTemplate>
                </CollectionView>
                <Button BackgroundColor="Gray" VerticalOptions="Center" Text="Hide some Items" Clicked="Button_Clicked"></Button>
            </StackLayout>
        </Grid>
    </ContentPage>
```
xaml.cs : (Clicked event)
```
 private void Button_Clicked(object sender, EventArgs e)
        {
            var viewModel = this.BindingContext as MainPageViewModel;
            viewModel.ObservableCollectionTest[1].IsVisible = !viewModel.ObservableCollectionTest[1].IsVisible;
            viewModel.ObservableCollectionTest[2].IsVisible = !viewModel.ObservableCollectionTest[2].IsVisible;
            viewModel.ObservableCollectionTest[3].IsVisible = !viewModel.ObservableCollectionTest[3].IsVisible;
            viewModel.ObservableCollectionTest[4].IsVisible = !viewModel.ObservableCollectionTest[4].IsVisible;
            viewModel.ObservableCollectionTest[5].IsVisible = !viewModel.ObservableCollectionTest[5].IsVisible;
            viewModel.ObservableCollectionTest[6].IsVisible = !viewModel.ObservableCollectionTest[6].IsVisible;
            viewModel.ObservableCollectionTest[7].IsVisible = !viewModel.ObservableCollectionTest[7].IsVisible;
            viewModel.ObservableCollectionTest[8].IsVisible = !viewModel.ObservableCollectionTest[8].IsVisible;
            viewModel.ObservableCollectionTest[9].IsVisible = !viewModel.ObservableCollectionTest[9].IsVisible;
            viewModel.ObservableCollectionTest[10].IsVisible = !viewModel.ObservableCollectionTest[10].IsVisible;
            viewModel.ObservableCollectionTest[11].IsVisible = !viewModel.ObservableCollectionTest[11].IsVisible;
            viewModel.ObservableCollectionTest[12].IsVisible = !viewModel.ObservableCollectionTest[12].IsVisible;
            viewModel.ObservableCollectionTest[13].IsVisible = !viewModel.ObservableCollectionTest[13].IsVisible;
            viewModel.ObservableCollectionTest[14].IsVisible = !viewModel.ObservableCollectionTest[14].IsVisible;
            viewModel.ObservableCollectionTest[15].IsVisible = !viewModel.ObservableCollectionTest[15].IsVisible;
            viewModel.ObservableCollectionTest[16].IsVisible = !viewModel.ObservableCollectionTest[16].IsVisible;
            viewModel.ObservableCollectionTest[17].IsVisible = !viewModel.ObservableCollectionTest[17].IsVisible;
            viewModel.ObservableCollectionTest[18].IsVisible = !viewModel.ObservableCollectionTest[18].IsVisible;
            viewModel.ObservableCollectionTest[19].IsVisible = !viewModel.ObservableCollectionTest[19].IsVisible;
            viewModel.ObservableCollectionTest[20].IsVisible = !viewModel.ObservableCollectionTest[20].IsVisible;
        }
```
VM: 
```
public static string ObservableCollectionTestPropertyName() { return nameof(ObservableCollectionTest); }
        private ObservableCollection<Item> _ObservableCollectionTest = new ObservableCollection<Item>(new List<Item>()
        {
            new Item("test 1")
            , new Item("test 2")
            , new Item("test 3")
            , new Item("test 4")
            , new Item("test 5")
            , new Item("test 6")
            , new Item("test 7")
            , new Item("test 8")
            , new Item("test 9")
            , new Item("test 10")
            , new Item("test 11")
            , new Item("test 12")
            , new Item("test 13")
            , new Item("test 14")
            , new Item("test 15")
            , new Item("test 16")
            , new Item("test 17")
            , new Item("test 18")
            , new Item("test 19")
            , new Item("test 20")
            , new Item("test 21")
            , new Item("test 22")
            , new Item("test 24")
            , new Item("test 25")
            , new Item("test 26")
            , new Item("test 27")
            , new Item("test 28")
            , new Item("test 29")
            , new Item("test 30")
            , new Item("test 31")
            , new Item("test 32")
            , new Item("test 33")
            , new Item("test 34")
            , new Item("test 35")
            , new Item("test 36")
            , new Item("test 37")
            , new Item("test 38")
            , new Item("test 39")
            , new Item("test 40")
        });
        public ObservableCollection<Item> ObservableCollectionTest
        {
            get
            {
                return _ObservableCollectionTest;
            }
            set
            {
                _ObservableCollectionTest = value;
                RaisePropertyChanged();
            }
        }
```
BoolToHeight converter: 
```
public class BoolToHeight : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            if (value != null) {
                if ((bool)value) {
                    return System.Convert.ToDouble((string)parameter);
                }
                else return 0;
            }
            else
                return 0;
        }
        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            if ((double)value == System.Convert.ToDouble((string)parameter)) return true;
            else return false;
        }
    }
```
### Expected Behavior
A hidden item should be not seleccionable and it should not take any space
### Actual Behavior
It takes space and it is seleccionable
### Basic Information
- Version with issue: 4.0.0.250467-pre7
- IDE: Visual Studio Community 2017 version 15.9.9
- Platform Target Frameworks: 

  - Android:  8.1
  - UWP:  Windows 10 version 1803 Build 17134

### Screenshots
UWP
CollectionView with all items visible:
![image](https://user-images.githubusercontent.com/5736566/54739683-4fb7f680-4bb9-11e9-8031-d216f9d6411c.png)

CollectionView with some items hidden (the gray line is an item selected after hidding the items) : 
![image](https://user-images.githubusercontent.com/5736566/54739929-061bdb80-4bba-11e9-968c-32358edb2712.png)

Android
CollectionView with all items visible :
![image](https://user-images.githubusercontent.com/5736566/54739808-a9b8bc00-4bb9-11e9-9145-dda62d2a8b8a.png)

CollectionView with some items hidden (the orange line is an item selected after hidding the items) :
![image](https://user-images.githubusercontent.com/5736566/54739887-e4baef80-4bb9-11e9-9bd8-dffe710e080c.png)

Source code: 
https://github.com/psp589/XamarinFormsIssuesReproduction

**Comment by samhouts** [comment]
@psp589 Do you happen to already have this in a project that we can use to test with? And is this one also only a problem on Android? Thanks!

**Comment by samhouts** [comment]
perhaps related to #4184, #4424, #5359

**Comment by psp589** [comment]
@samhouts  Hello, no, it is not only a problem on Android, is in both Android and UWP.
I'll create a github repo with a project reproducing the problem.

**Comment by psp589** [comment]
See https://github.com/psp589/XamarinFormsIssuesReproduction

**Comment by boris-df** [comment]
I stumbled across this problem today :/ I thought i could hide some menu-items with this IsVisible and binding... but nope ...

No workarounds so far, right? So i think i have to rebuild the List everytime i like to hide/show some item. Not elegant but i may work for me as a workaround.

**Comment by lafritay** [comment]
@PureWeen @samhouts This still doesn't work for me in 4.7. Is that expected?

**Comment by hartez** [comment]
> @PureWeen @samhouts This still doesn't work for me in 4.7. Is that expected?

No, that's very much not expected - this was fixed back in ... 4.2, I think.

If you're experiencing the same problem or something similar, please open a new issue with details and we'll take a look.

**Comment by lafritay** [comment]
@PureWeen My specific case might be a bit special. The item in question is visible on initial render but then a user action causes it to become invisible. I see the content disappear but the space taken up by the card does not go away. Would you expect that to work?

**Comment by PureWeen** [comment]
@lafritay I'd need a little more detail to know if it is or isn't

Can you open a new issue with a repro that we can take a look at to see if this is a bug or not?

**Comment by Sourceasaurus** [comment]
This is still an issue in 4.8 for me as well (Android and iOS).  I have a simple switch that sets visibility for news items bound to a CollectionView item source.  My implementation is roughly the same as the OP's example.  Like the OP, I'm also using HeightRequest to keep items consistent.

```
HeightRequest="{Binding Converter={StaticResource PercentHeightConverter}, ConverterParameter={StaticResource newsItemHeight}}"
```

This was resolved to #5905, which would not have been sufficient to address this issue in my scenario because my items aren't dynamically sized to the content.

@lafritay @boris-df A decent, albeit heavy-handed workaround, is to use triggers to force values to 0 when the item is hidden.  In my case, it's usually height, padding and margin.

```
  <Frame HeightRequest="{Binding Converter={StaticResource PercentHeightConverter}, ConverterParameter={StaticResource newsItemHeight}}"
         Padding="3"
         HasShadow="False"
         Margin="2"
         IsVisible="{Binding IsVisible}">
       <Frame.Triggers>
             <!-- Height -->
             <Trigger TargetType="Frame"
                      Property="IsVisible"
                      Value="False">
                 <Setter Property="HeightRequest"
                         Value="0" />
                  </Trigger>

             <!-- Padding -->
             <Trigger TargetType="Frame"
                      Property="IsVisible"
                      Value="False">
                 <Setter Property="Padding"
                         Value="0" />
                  </Trigger>

             <!-- Margin -->
             <Trigger TargetType="Frame"
                      Property="IsVisible"
                      Value="False">
                 <Setter Property="Margin"
                         Value="0" />
                  </Trigger>
       </Frame.Triggers>
    <!-- <item content> -->
  </Frame>
```

**Comment by hartez** [comment]
@Sourceasaurus Could you open a new issue with the information you posted here? Thanks.

**Comment by Sourceasaurus** [comment]
@hartez, this bug already describes the exact issue and the OP provided a clear repro.  It should be reopened, as it was incorrectly closed.

Here are my current config details:
- Xamarin Version: v4.8.0.1269
- IDE: Visual Studio Community 2019  v16.7.4
- Affected Platforms:  Android, iOS

**Comment by jeff-gaskill** [comment]
> I stumbled across this problem today :/ I thought i could hide some menu-items with this IsVisible and binding... but nope ...
> 
> No workarounds so far, right? So i think i have to rebuild the List everytime i like to hide/show some item. Not elegant but i may work for me as a workaround.

Did you try toggling the HeightRequest?  The behavior you want is equivalent to the WPF Collapsed enum.  A data trigger or a converter can be used to toggle height from 0 - preset height based on a bool.

**Comment by Suplanus** [comment]
Also in 5.0.0

**Comment by VWilcox2000** [comment]
I used the ItemHeight binding updates to hide items filtered out, but found the CollectionView (on iOS at least) was not properly compressing items even with margins and height all zeroed out.  A solution that works reliably is to use a template selector.  Whenever filter text is updated, re-instantiate the template selector passing the text into the constructor.  This will cause the collection view to re-select template for all items.  For items that do not match your filter, rather than providing the standard template, provide another view that has 0 height and has IsVisible set to false.  This is more reliable than changing height and more responsive than swapping out collections.
