### ISSUE TITLE
[Bug] ListView showing empty items on XF4

### ISSUE THREAD

**Issue by itoledo** [xamarin/Xamarin.Forms#6439]
### Description
ListView shows empty cells, worked fine in XF3.6 and older.

### Steps to Reproduce

1. clone the repo at https://github.com/itoledo/XF4ListBug (it's the MasterDetail template with changes extracted from the app I'm working on)
2. check the ItemsViewModel.cs for the code. I'm using a DataTemplateSelector, which always selects the same template.
3. run the app and scroll down.

### Expected Behavior
List shows all the cells with content.

### Actual Behavior
After scrolling, some cells are empty.

### Basic Information

- Version with issue: Xamarin.Forms 4.0.0.482894
- Last known good version: Xamarin.Forms 3.6.0.264807 (later versions have the iOS 10 cell height bug)
- IDE: VS2019 16.1.2
- Platform Target Frameworks: 
  - Android: 9.0
- Affected Devices: tested on my Nokia 7.1 with Android 9

### Screenshots
https://gfycat.com/lateshoddyaquaticleech

### Reproduction Link
https://github.com/itoledo/XF4ListBug

**Comment by mabdollahiasl** [comment]
I have this problem too,
is a temporary fix available or I have to downgrade to 3.6?

**Comment by jonathanantoine** [comment]
Would like to have a temp fix too... :(

**Comment by psg107** [comment]
Set 'ListViewCachingStrategy' Option to 'RecycleElement' is solved this problem maybe.
but other listview bug exist in XF 4.0
you should downgrade XF version to 3.6

https://github.com/xamarin/Xamarin.Forms/issues/6447

**Comment by LeoJHarris** [comment]
Also like to see this fixed, this is causing us some headache atm.

**Comment by mekangarayev** [comment]
same problem still exists on version xamarin forms 4.1

**Comment by samhouts** [comment]
closed by #6390

**Comment by ssone95** [comment]
Still not resolved, even on Xamarin Forms 4.2
I tried it when Swipe to refresh is enabled, if I swipe down without scrolling, it works as intended, but as soon as I start scrolling, whenever I swipe, content disappears from list items.
