### ISSUE TITLE
[Bug] ListView DataTemplate Label text cutting in Xamarin.Forms 4.0

### ISSUE THREAD

**Issue by M-Narender-Reddy** [xamarin/Xamarin.Forms#6447]
### Description
List view with data template and binding data from view model. If the value of a label changes dynamically from a converter, the lebel is cutting. The same code was working before upgrading to xamrin.forms 4.0

### Steps to Reproduce

1. Create a list view with data template view cell
2. Bind a collection of model objects to the list items source
3. Have a property in the view model which is assigned from a converter based on its value.

### Expected Behavior

The label which is updating from converter should be visible on the view.

### Actual Behavior
The label which is updating from converter is cutting and showing ellipses at the end.
### Basic Information

- Version with issue: 4.0 
- Last known good version: 3.6
- IDE: VS 2017
- Platform Target Frameworks: 
  - iOS:  
  - Android:  9.0
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

![Screenshot_20190607-183632](https://user-images.githubusercontent.com/51481908/59107549-8569b180-8956-11e9-8f4a-a31ac2656a0c.jpg)

### Reproduction Link

https://github.com/M-Narender-Reddy/MyRepo

**Comment by samhouts** [comment]
Duplicate of #3150

**Comment by M-Narender-Reddy** [comment]
@samhouts this bug not looking like duplicate to the bug [#3150 ](https://github.com/xamarin/Xamarin.Forms/issues/3150).

**In the below 2 cases this issue is not seen:**
1. Remove converter and just use simple binding.
2. Use label without enclosing it inside a stack layout by removing horizontaloptions property from label.

I tried by using StackLayout in place of Frame and this but still exists. Wondering how this bug this has been closed as duplicate to #3150

**Comment by samhouts** [comment]
@M-Narender-Reddy Confirmed! Thanks

**Comment by M-Narender-Reddy** [comment]
@samhouts @davidortinau @PureWeen I tried by updating xamarin forms to latest stable (Version 4.0.0.497661) but, this issue still exists, could someone look into this please.

**Comment by davidortinau** [comment]
@M-Narender-Reddy pretty sure this hasn't shipped as the fix was merged 3 days ago and latest stable is 8 days old. It'll be in the next service release

**Comment by samhouts** [comment]
@M-Narender-Reddy @davidortinau This was closed in error. We're still working on it. Thanks!

**Comment by MitchBomcanhao** [comment]
This is referenced in the release notes for 4.0.0 sr4 as being fixed, and indeed it doesn't appear to be fixed.
could the release notes be corrected?

**Comment by M-Narender-Reddy** [comment]
@samhouts @davidortinau Any update on this one please, is this fixed in latest version ?

**Comment by PureWeen** [comment]
This will be fixed as part of this PR
https://github.com/xamarin/Xamarin.Forms/pull/6390

**Comment by samhouts** [comment]
closed by #6390

**Comment by PouryaNoufallah96** [comment]
its still not fixed i updated to pre release today . when i scroll my listview labels are cutting :(:( 
https://pasteboard.co/IovW3rJ.png
https://pasteboard.co/IovVk2o.png
