### ISSUE TITLE
[Bug] Shell - First page in AppShell ignores the UseSafeAreaInset flag

### ISSUE THREAD

**Issue by seansparkman** [xamarin/Xamarin.Forms#6499]
### Description

Shell does not seem to respect the `UseSafeAreaInset` flag and overrides the `Padding` of the first `ContentPage` in a tab or flyout.

### Steps to Reproduce

1. Run the sample project below
2. See the `ContentPage`'s light purple background above and below the lavendar `StackLayout`.
3. Click on the "Next Screen" button
4. See the the second screen does not show the `ContentPage`'s background.  You can only see the `StackLayout`'s background color.

### Expected Behavior

The `ContentPage`'s content should take up the whole screen.  In the example, `StackLayout` should take up the whole screen.

### Actual Behavior

The `ContentPage` has `Padding` set to the `SafeAreaInset` values.  This means that the content inside the page does not take up the whole screen.

### Basic Information

- Version with issue: 4.0.0.482894
- Last known good version: N/A
- IDE: Visual Studio 2019 for Windows 16.1.2
- Platform Target Frameworks: 
  - iOS:  12.10.0.153
  - Android: N/A
  - UWP:  N/A
- Android Support Library Version: N/A
- Nuget Packages: Just what comes with the template
- Affected Devices:

### Screenshots

![2019-06-11_03-30-41-PM](https://user-images.githubusercontent.com/991351/59304464-eeef0600-8c5d-11e9-97dc-2b3a0563e51e.png)
![2019-06-11_03-30-44-PM](https://user-images.githubusercontent.com/991351/59304469-f0b8c980-8c5d-11e9-9fb5-a28b638f6643.png)

### Reproduction Link

https://github.com/seansparkman/ShellNavigationExample/tree/use-safe-area-ignored
https://github.com/seansparkman/ShellNavigationExample/blob/use-safe-area-ignored/ShellNavigationRegistration/ShellNavigationRegistration/Views/OnBoarding.xaml#L13

**Comment by seansparkman** [comment]
I found where this is being set finally.  It looks like @PureWeen added it.
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs#L354-L365

**Comment by PureWeen** [comment]
@seansparkman this PR should resolve the issue for you

https://github.com/xamarin/Xamarin.Forms/pull/6457

**Comment by seansparkman** [comment]
Thanks @PureWeen!  Apparently, my search-fu isn't strong enough.

**Comment by seansparkman** [comment]
A work around...
https://gist.github.com/seansparkman/0668871d1dab1c1e7d1fcf3da8cbac33

**Comment by seansparkman** [comment]
I am still seeing this issue in 4.2.0.815419.  UseSafeArea is being ignored.

```
xmlns:ios="clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core" 
ios:Page.UseSafeArea="false"
```
