### ISSUE TITLE
UWP build error

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/Xamarin.Forms#7262]
Error		Payload file 'Packages\xamarin.forms\4.3.0.1032-nightly\lib\uap10.0\Xamarin.Forms.Platform.UAP\CollectionView\ItemsViewStyles.xbf' does not exist.			

I do not use CollectionView  in my application

**Comment by PureWeen** [comment]
Fixed here https://github.com/xamarin/Xamarin.Forms/pull/7189

**Comment by VladislavAntonyuk** [comment]
@PureWeen I am using 4.3.0.1032-nightly. Is it build before PR merged?

**Comment by PureWeen** [comment]
Yes that one is from 8/10 and the PR to fix this was merged 8/16

checking now why nightlies aren't going out

**Comment by VladislavAntonyuk** [comment]
@PureWeen any updates? Nightlies are still not accessible since build 1032
