### ISSUE TITLE
Time lag before closing Shell flyout menu

### ISSUE THREAD

**Issue by gnout** [xamarin/Xamarin.Forms#7521]
# Description

I created a new project in VS just by choosing the Shell template. I converted the AppShell to have `flyout` menus instead of tabs.   
In the attached screen cast, when I tapped on the item that is currently displayed (the first tap is on the about page) then the side menu closes very smoothly which is the expected behavior.  
When I tap on the second item (which is not currently displayed) then there is lag before the side menu closes. It seems as if the app is frozen for a few milliseconds.

### Expected Behavior

I was expecting the closing of the side menu, in all cases, to be smooth

### Actual Behavior

When tapping on one of the flyout menu items (not the one that is currently visible), there is a time lag before the flyout menu is closed and it looks (for a few miliseconds) that is app freezes. This behavior is displayed also to views that don;t have any data (i.e the About page)

### Basic Information

- Version with issue: 4.2.0.778463
- Last known good version:
- IDE:
- Platform Target Frameworks:
  - Android: 9.0
- Android Support Library Version: 28.0.01
- Affected Devices: Nokia one 3.1, Samsung Galaxy J3

### Screenshots

Screen cats is from an actual device and not an emulator

[screencast.zip](https://github.com/xamarin/Xamarin.Forms/files/3613038/screencast.zip)

**Comment by lv1il0s** [comment]
Seems related to https://github.com/xamarin/Xamarin.Forms/issues/5216 (which is closed but apparently not resolved). I'm experiencing the same issue on physical devices (Samsung S8, A3, Sony Z1 Compact) and emulators. On the other hand, iOS seems to be smooth. I hope this issue will be looked into soon.

**Comment by wagenheimer** [comment]
I also have this problem!

**Comment by Mikilll94** [comment]
Is it going to be fixed? This problem exists from the very beginning and it makes flyout unusable.

**Comment by denzerd** [comment]
I have the same problem with a really simple setup.
I assume this won't be fixed it is the same bad behaviour as it was for many years with the MasterDetailPage.
The problem is that the rendering of the underlying ContentPage takes that much time that the animation of the menu is interrupted. 
I'm looking for a way to apply the MasterDetailPage workaround to this, no luck so far.

**Comment by VirtualNomad00** [comment]
Guess it's still not solved, which is a bit frustrating as this is a major UX issue

**Comment by Mikilll94** [comment]
@samhouts @jfversluis @davidortinau

**Comment by RedChops** [comment]
Moving all pages except for one top level `ShellContent` from the Flyout Menu to `MenuItem`, navigating to them with `GoToAsync`, and manually closing the menu is significantly more performant. It's crazy, the performance by going this route is probably on-par with the iOS experience.

There is still an always noticeable shutter when going back to the home page which looks pretty sloppy. This is very unfortunate, especially since it seems like navigation is pretty central to the whole Shell interface. It appears to be a performance hitch related to pushing a new page on to the root of the navigation stack alone.

**Comment by RedChops** [comment]
Found some additional info, but it doesn't really help my design very much:

The lag returning to the home screen does not occur if the page I'm returning from was created by executing `Navigation.PushModalAsync()`. The transition is nice and smooth. If I navigate to a page using `Shell.Current.GoToAsync()`, the transition to the page is nice and smooth, but the transition back always hitches. The animation of the flyout menu doesn't seem to be involved.

I also noticed that when I'm navigating back to the home page, it is very obviously being fully reinstantiated every time. This is nothing special though I guess. I put a debug statement in several pages refresh commands in my app, the command should only get executed on first navigation or if  the user pulls to refresh, except it gets called every time the pages are navigated to. I've registered all routes outside of the home route using ex. `Routing.RegisterRoute("monkeydetails", typeof(MonkeyDetailPage));`, does that not keep the page in memory after it's loaded the first time? Doesn't really help the `ShellContent`/ home page situation though, as realistically that page should always be in memory.

**Comment by DanKyungu** [comment]
@PureWeen, can you have an alternative to avoid this lag because we must go in production and i need to know if there is something we can do, if not we'll have to move the default MasterDetail Navigation...

**Comment by Mikilll94** [comment]
@DanKyungu 
It seems that there is no workaround. You need to go back to the old Master Detail page.

It's very sad that the Xamarin team is enjoyed with the Shell but with this bug, the Shell is unusable because I cannot use the flyout.

**Comment by wagenheimer** [comment]
This bug is really annoying! I don't understand why something so critical seems to be ignored.

**Comment by samhouts** [comment]
We're definitely not ignoring it! We've marked this as one of our highest priority Shell issues to resolve in the near future. If we discover a workaround in the meantime, we will post it here.  Thanks for your patience!

**Comment by Jason424242** [comment]
I have also noticed a similar looking stutter on the Google Play store and the Outlook app.  Google Play store especially when I select "My Apps & games" off the menu.  Outlook sometimes when I choose a new folder.  I thought it may be an inherent Android problem when starting a network fetch while an animation is running.

**Comment by nhadro** [comment]
Really a big issue for us.  We have to release in a month, any idea if something might be in place to fix that before then?  I really don't want to go back to MasterDetail.

**Comment by tossingc** [comment]
I have a workaround - it's not pretty, but it works.

It looks like the problem is that there is too much going on in the main thread while the flyout close transition is trying to run. (Android DrawerLayout CloseDrawer() animation)

NOTE: this workaround addresses the Xamarin Forms logic for creating and setting the page blocking the UI thread, but anything other app logic running on the UI thread will cause the same jittery "close drawer" animation. One way to mitigate this would be to listen for FlyoutIsPresented to become true and pause any update logic running on the UI thread during that time.

In your subclass of Shell:

1. override OnPropertyChanged and store the last time the FlyoutIsPresented property was set to false
2. override OnNavigating and if the last time the FlyoutIsPresented property was set to false is less than some value (using 1000ms in the code below), then assume the Flyout was just hidden and perform the following:
3. cancel the navigation
4. set FlyoutIsPresented to false
5. raise OnPropertyChanged for the FlyoutIsPresented to trigger the ShellFlyoutRenderer to close the drawer
6. wait a brief period for the flyout to close
7. set a flag that we cancelled the navigation so we know to skip this check on the next call to OnNavigating
8. re-run the original navigation in the arguments passed to OnNavigating the first time

```
	public class AppShell : Shell
	{
		...
		
        private DateTime LastFlyoutHiddenUtcDateTime { get; set; }

        protected override void OnPropertyChanged(string propertyName = null)
        {
            base.OnPropertyChanged(propertyName);

            if (propertyName == nameof(FlyoutIsPresented))
            {
                if (!FlyoutIsPresented)
                {
                    LastFlyoutHiddenUtcDateTime = DateTime.UtcNow;
                }
            }
        }

        private bool WasNavigationCancelledToCloseFlyoutAndReRunAfterADelayToAvoidJitteryFlyoutCloseTransitionBug = false;

        protected override async void OnNavigating(ShellNavigatingEventArgs args)
        {
            if (!WasNavigationCancelledToCloseFlyoutAndReRunAfterADelayToAvoidJitteryFlyoutCloseTransitionBug)
            {
				// if the above value is true, then this is the re-run navigation that the GoToAsync(args.Target) call below - skip this block this pass through
                if ((DateTime.UtcNow - LastFlyoutHiddenUtcDateTime).TotalMilliseconds < 1000)
                {
                    args.Cancel();

                    FlyoutIsPresented = false;

                    OnPropertyChanged(nameof(FlyoutIsPresented));

                    await Task.Delay(300);

                    WasNavigationCancelledToCloseFlyoutAndReRunAfterADelayToAvoidJitteryFlyoutCloseTransitionBug = true;

                    // re-run the originally requested navigation
                    await GoToAsync(args.Target);

                    return;
                }
            }

            WasNavigationCancelledToCloseFlyoutAndReRunAfterADelayToAvoidJitteryFlyoutCloseTransitionBug = false;

            base.OnNavigating(args);
		}
		
		...
	}

```

@nhadro @wagenheimer @Mikilll94 @DanKyungu @VirtualNomad00 @denzerd @lv1il0s @gnout

**Comment by whitedevils** [comment]
news about resolution? is very annoying this problem. :(

**Comment by JAdeloye** [comment]
Any update on this, has been here a while and really should be resolved?

**Comment by stavroaudi** [comment]
Why returned to backlog? This should be the very first priority because it essentially prevents anyone who wants to release a half-decent app from using Shell.

**Comment by denzerd** [comment]
@tossingc 
Thank you, somehow I saw your comment only now (Github mails go to spam in my mail account apparently)
However, back in the days I managed to have the same result as I have with your solution by simply doing this in the AppShell.cs

`protected async override void OnPropertyChanged([CallerMemberName] string propertyName = null)
{
 if (propertyName.Equals("CurrentItem") && Device.RuntimePlatform == Device.Android)
            {
                FlyoutIsPresented = false;
                await Task.Delay(300);
            }
            base.OnPropertyChanged(propertyName);
}`

I would really love to see this issue officially fixed!

**Comment by holecekp** [comment]
I have tried denzerd's workaround. Unfortunately, I could not use it because it introduces a new problem - after the shell menu is closed, there is still the old page displayed and it takes a surprisingly long time (1-2 seconds) before the new one appears. Tested on XF 4.8 Service Release 1.

I would also really like to see an official fix. This is an important issue.  It results in poor user experience for Android applications that use shell. It is strange because everything is super fast on UWP.

**Comment by stavroaudi** [comment]
Same here. I’m using it right now but would like to see it fixed officially. Using the workaround for now.

Stavro

**Comment by DanKyungu** [comment]
Until now, i suggest to use MasterDetailPage

**Comment by lv1il0s** [comment]
How can we be confident in choosing Xamarin for cross-platform development when a glaring issue like this one hasn't been addressed for over a year?

**Comment by coommark** [comment]
Any temporary workaround for this? I have a production ready app, but this has become a big issue for us.

**Comment by Nelo-cool** [comment]
> Any temporary workaround for this? I have a production ready app, but this has become a big issue for us.

No.

**Comment by codebreakerlegend2019** [comment]
Any updates??? Still experiencing this

**Comment by DanKyungu** [comment]
You can use LazyView to control the delay, 
https://www.sharpnado.com/xamarin-forms-lazyview-boost-your-app-reactivity-and-startup-time/

**Comment by AndreasReitberger** [comment]
I'm still facing this issue. Anything new on this one? iOS is working fine, only Android is lagging behind...
Thanks!

**Comment by fazary** [comment]
Opened from one year !
Nice team from Microsoft 👍

**Comment by Nelo-cool** [comment]
> Opened from one year !
> Nice team from Microsoft 👍

Good boys! :) 🥇

**Comment by subhadrajain** [comment]
Please fix this.
I will lose my client

**Comment by pictos** [comment]
@subhadrajain does this workaround doesn't work for you?https://github.com/xamarin/Xamarin.Forms/issues/7521#issuecomment-660948841

**Comment by holecekp** [comment]
I have tried the mentioned workaround and it did not work for me. It fixed the animation, but instead, it introduced a big lag before the new page was opened. So the overall user experience was equally bad :-(

**Comment by pictos** [comment]
@holecekp this one also? https://github.com/xamarin/Xamarin.Forms/issues/7521#issuecomment-606971122

Also, could you share a repro? I couldn't reproduce this issue locally in any Shell app that I made.

**Comment by subhadrajain** [comment]
@pictos 7 out of 10 times it is working fine.

**Comment by sparer** [comment]
I've produced this workaround which works sufficiently for my application. It just waits for the page to load before hiding the flyout. My app has a redirect when the app loads to request permissions if the app doesn't have them hence the 'redirected' bool. This was necessary because the flyout would show on a redirect even though the user hadn't clicked the hamburger icon. I can see that it might not work in some scenarios, such as long loading page, but as I said, for me it solves the problem sufficiently.
```
        private bool redirected;

        protected override void OnNavigating(ShellNavigatingEventArgs args)
        {
            if (Device.Android.Equals(Device.RuntimePlatform))
            {
                if (ShellNavigationSource.ShellSectionChanged.Equals(args.Source) && !redirected)
                {
                    FlyoutIsPresented = true;
                }
                redirected = true;
            }
            base.OnNavigating(args);
        }

        protected override void OnNavigated(ShellNavigatedEventArgs args)
        {
            if (Device.Android.Equals(Device.RuntimePlatform))
            {
                FlyoutIsPresented = false;
                redirected = false;
            }
            base.OnNavigated(args);
        }
```

**Comment by Jose-Develaw** [comment]
Hi, everyone:

I have modified a bit some code I saw here and I obtained a pretty good result. Try this: 

```
protected async override void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            base.OnPropertyChanged(propertyName);
            var shell = this;
            if (propertyName.Equals("CurrentItem") && Device.RuntimePlatform == Device.Android && this.CurrentState?.Location.OriginalString != "//loginPage")
            {
                FlyoutIsPresented = true;
                await Task.Delay(300);
                FlyoutIsPresented = false;
                
            }
          
        }
```

The 'this.CurrentState?.Location.OriginalString != "//loginPage"' thing is to avoid the flyout menu to appear the first time I logged in.

Let me know it this works for you

**Comment by Reddyo** [comment]
Also hoping this gets an official fix.. I had to combine some of the solutions here to get something that worked for me. Primarily it is Jose-Develaw's solution just above, but adding the extra condition did not stop the flyout from opening on startup for me. I also did not like the idea of omitting the fix for certain pages, so I changed it like so to avoid it triggering at startup:

```
bool startUp = true;
protected override void OnNavigated(ShellNavigatedEventArgs args)
{
    base.OnNavigated(args);
    startUp = false;
}

protected async override void OnPropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
{
    base.OnPropertyChanged(propertyName);
    if (!startUp && propertyName.Equals("CurrentItem") && Device.RuntimePlatform == Device.Android)
    {
        FlyoutIsPresented = true;
        await System.Threading.Tasks.Task.Delay(300);
        FlyoutIsPresented = false;
    }
}
```
OnNavigated() gets called after the initial calls to OnPropertyChanged() for "CurrentItem" so that is where the "startup" flag is updated to false.

**Comment by angelru** [comment]
The same problem here, it seems to also have to do with the links on the page being loaded. I put a delay before "refresh my view" and it just finishes closing the menu and doesn't freeze while animating.

**Comment by RaghebAlashqar** [comment]
> 
> 
> Also hoping this gets an official fix.. I had to combine some of the solutions here to get something that worked for me. Primarily it is Jose-Develaw's solution just above, but adding the extra condition did not stop the flyout from opening on startup for me. I also did not like the idea of omitting the fix for certain pages, so I changed it like so to avoid it triggering at startup:
> 
> ```
> bool startUp = true;
> protected override void OnNavigated(ShellNavigatedEventArgs args)
> {
>     base.OnNavigated(args);
>     startUp = false;
> }
> 
> protected async override void OnPropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
> {
>     base.OnPropertyChanged(propertyName);
>     if (!startUp && propertyName.Equals("CurrentItem") && Device.RuntimePlatform == Device.Android)
>     {
>         FlyoutIsPresented = true;
>         await System.Threading.Tasks.Task.Delay(300);
>         FlyoutIsPresented = false;
>     }
> }
> ```
> 
> OnNavigated() gets called after the initial calls to OnPropertyChanged() for "CurrentItem" so that is where the "startup" flag is updated to false.

Just tried this, It helped so much, No lagging and smooth transition. 
Thank you very much

**Comment by AndreasReitberger** [comment]
@jsuarezruiz @hartez 
Is this getting an official fix with SR5? This issue is almost open for two years..

**Comment by Nelo-cool** [comment]
> 
> 
> @jsuarezruiz @hartez
> Is this getting an official fix with SR5? This issue is almost open for two years..

There is a good saying among Russians. They have been waiting for the promised three years:)

**Comment by andersondamasio** [comment]
I also have this problem.
Any definitive solution?

**Comment by angelru** [comment]
Maybe in MAUI it is corrected.

**Comment by Darlingtone** [comment]
I seriously hope so

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by PureWeen** [comment]
> Maybe in MAUI it is corrected.

It should be a lot better right now in MAUI. One of the issues here is that on XF shell aggressively disposes and recreates renderers every time you move between tabs/flyout items. With MAUI we aren't doing that and as you move around the native stacks are all maintained. 

If anyone is up for testing this out a bit on MAUI let me know your results.

**Comment by codebreakerlegend2019** [comment]
To be fair for the one that is still on XF this should be fixed. Just saying.

**Comment by NemesisXB** [comment]
Another 6 months has past and still not fixed?

**Comment by NeilWork** [comment]
All the fixes presented here merely delays the lag to another point or hides it behind the flyout menu. Is there not a way to preload pages and just present them to a detail page similar to what the MasterDetail page did

**Comment by supershopping** [comment]
Finally I found this long thread… I was having this issue on XF. Now I move on to MAUI, still the similar experience. Anyone has comments or solutions for MAUI performance?

**Comment by kdgilang** [comment]
Please fix this, I'm still facing the same issue on XS & MAUI.

**Comment by Hardikzinzala** [comment]
Please fix this, I'm still facing the same issue on MAUI.
