### ISSUE TITLE
[Bug] Hot Reload: TabbedPage adds a new copy of tabs when reloaded

### ISSUE THREAD

**Issue by mfeingol** [xamarin/Xamarin.Forms#7741]
### Steps to Reproduce

1. Create new tabbed project in VS 2019
2. Enable Hot Reload
2. Run app in debugger (on Android, at least)
2. Edit and save MainPage.xaml, observe page reloads in debugger
3. Observe page now has four tabs

### Expected Behavior

Old tabs would be cleared

### Actual Behavior

Old tabs are retained alongside new tabs

### Basic Information

- Version with issue: 4.2.0.815419
- Last known good version: Unknown
- IDE: VS 2019 16.3
- Platform Target Frameworks: 
  - Android: 9.0
- Android Support Library Version: 28.0.0.3
- Nuget Packages:
- Affected Devices: Android emulators

### Reproduction Link

Can provide repro on demand. It's very easy to observe with VS-generated tabbed project.

**Comment by StephaneDelcroix** [comment]
this is fixed in newer versions of HR

**Comment by mfeingol** [comment]
Thanks, @StephaneDelcroix. Would the fix be part of an XF release, or part of VS?

**Comment by avatar2012** [comment]
This issue still remains on reacent VS2019. Any suggention?

**Comment by AedDev** [comment]
Still facing this issue in VS 2019 with the currently latest version of Xamarin.Forms installed :(

**Comment by carlosernestolopez** [comment]
"this is fixed in newer versions of HR" false still facing this issue

**Comment by ForeverFast** [comment]
still relevant, VS2019

**Comment by GiampaoloGabba** [comment]
why is this closed? the bug is always here... alive and kickin!!!

**Comment by skaman** [comment]
Any workaround for this?

**Comment by TFreudi1** [comment]
The bug is still there in 16.6.4, also the Hot Reload Option "Only view changes" (Forms > 4.5.0.17) did'nt work with tabbed pages.

**Comment by GiampaoloGabba** [comment]
the fix is coming to us :) They finally fixed in in their internal build: https://developercommunity.visualstudio.com/comments/1120409/view.html

**Comment by emersonk** [comment]
Is anyone else still having this problem?

**Comment by mfeingol** [comment]
Yep, I saw this repro just the other day with latest VS and XF 5.0.

**Comment by robertsan96** [comment]
Still happening in VS for macOS (both Android & iOS)... 👎

**Comment by mfeingol** [comment]
@StephaneDelcroix: this needs to be reopened.

**Comment by TFreudi1** [comment]
Same thing for me, please reopen it is not solved.

**Comment by darm10** [comment]
This is still broken with the latest v16.10.2

**Comment by elleyer** [comment]
Have the same issue right now. Seems to be broken.

**Comment by davidlopez9210** [comment]
Still with the same problem. There is no a real solution apparently
