### ISSUE TITLE
[Bug] Selection event not working fine when we use swipeview with Listiew

### ISSUE THREAD

**Issue by chinni-nag** [xamarin/Xamarin.Forms#9466]
### Description
I tried the swipeview sample,   Swipe from left to right and right to left working fine. But when i try to execute the command parameter or selection of that one item in list sele
![Swipeview issue](https://user-images.githubusercontent.com/52288258/74038097-9b4bdc80-49e5-11ea-9099-6ba91cd67932.png)
ction is not working . For instance am attaching the screen shot about the issue, below screen shot you can find the 3 dots symbol and small plus icon so those click are not working fine after add swipe view. Please let me know. Thanks.

### Steps to Reproduce

1. Try to add swipeview with Listview
2. Try to add buttons in item in listview
3. Perform command parameter 

### Expected Behavior
It should be work click event also
### Actual Behavior
Command parameters not working fine 
### Basic Information

- Version with issue: 4.4 Xamarin forms
- Last known good version: 4.3
- IDE:Visual studio 2019
- Platform Target Frameworks: 
  - iOS:  Working fine
  - Android: Not working fine
  -
- Android Support Library Version: 9

- Affected Devices: Oppo

### Screenshots :- Attached
![Swipeview issue](https://user-images.githubusercontent.com/52288258/74038429-2f1da880-49e6-11ea-8e0e-50a14130f46c.png)

**Comment by samhouts** [comment]
@chinni-nag Please try with the latest version of 4.4.0.  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by chinni-nag** [comment]
Hello @samhouts  Thanks for your reply. Please find below code i have written for swipeview.

 <renderedViews:HorizontalListView
                        x:Name="QueueListTapped"
                        Margin="0"
                        AbsoluteLayout.LayoutBounds="0,0,1,1"
                        AbsoluteLayout.LayoutFlags="All"
                        BackgroundColor="#E5E5E5"
                        ColumnCount="1"
                        EnableDragAndDrop="True"
                        ItemHeight="120"
                        ItemsSource="{Binding QueueData}"
                        ListLayout="Grid"
                        Style="{StaticResource HorizontalListView}">
                        <renderedViews:HorizontalListView.ItemTemplate>
                            <DataTemplate>
                                <renderedViews:DraggableViewCell x:Name="DraggableViewCell">
                                    <SwipeView
                                        Margin="0"
                                        Padding="0"
                                        HeightRequest="120">
                                        <SwipeView.RightItems>
                                            <SwipeItems Mode="Reveal">
                                                <SwipeItem
                                                    BackgroundColor="LightGreen"
                                                    IconImageSource="discuss"
                                                    Text="Favorite" />
                                            </SwipeItems>
                                        </SwipeView.RightItems>
                                        <controls:TappableGrid
                                            Margin="0"
                                            Padding="0"
                                            Tapped="QueueItemMultiSelectTapped"
                                            TappedParameter="{Binding .}">
                                            <Grid.ColumnDefinitions>
                                                <ColumnDefinition Width="*" />
                                                <ColumnDefinition Width="0" />
                                            </Grid.ColumnDefinitions>
                                            <controls:TappableFrame
                                                Grid.Row="0"
                                                Grid.Column="0"
                                                Margin="7,5,7,0"
                                                Padding="8"
                                                CornerRadius="5"
                                                HasShadow="True"
                                                OutlineColor="{Binding IsSelected, Converter={StaticResource UserTypeBGSelectedConverter}}"
                                                Tapped="QueueItemMultiSelectTapped"
                                                TappedParameter="{Binding .}">
                                                <controls:TappableGrid
                                                    ColumnSpacing="0"
                                                    RowSpacing="0"
                                                    Tapped="QueueItemMultiSelectTapped"
                                                    TappedParameter="{Binding .}">
                                                    <Grid.ColumnDefinitions>
                                                        <ColumnDefinition Width="25" />
                                                        <ColumnDefinition Width="*" />
                                                    </Grid.ColumnDefinitions>
                                                    <Image
                                                        Grid.Row="0"
                                                        Grid.Column="0"
                                                        HorizontalOptions="StartAndExpand"
                                                        Source="dragndrop"
                                                        VerticalOptions="CenterAndExpand" />

                                                    
                                                    <helpers:SwipeGesture
                                                        Grid.Row="0"
                                                        Grid.Column="1"
                                                        CommandParameter="{Binding .}"
                                                        SwipeLeft="GridTemplate_SwipeLeft"
                                                        SwipeRight="GridTemplate_SwipeRight">
                                                        <Grid.ColumnDefinitions>
                                                            <ColumnDefinition Width="130" />
                                                            <ColumnDefinition Width="*" />
                                                        </Grid.ColumnDefinitions>
                                                        <controls:TappableFrame
                                                            Grid.Row="0"
                                                            Grid.Column="0"
                                                            Margin="0"
                                                            Padding="0"
                                                            CornerRadius="2"
                                                            IsVisible="{Binding Video.IsNotWorkout}"
                                                            Tapped="QueueItemMultiSelectTapped"
                                                            TappedParameter="{Binding .}">
                                                            <ffimage:CachedImage
                                                                Aspect="AspectFill"
                                                                BitmapOptimizations="True"
                                                                DownsampleToViewSize="True"
                                                                RetryCount="6"
                                                                RetryDelay="400"
                                                                Source="{Binding Video.Thumbnail}"
                                                                VerticalOptions="FillAndExpand" />
                                                        </controls:TappableFrame>
                                                        <controls:TappableFrame
                                                            Grid.Row="0"
                                                            Grid.Column="0"
                                                            Margin="0"
                                                            Padding="0"
                                                            CornerRadius="2"
                                                            IsVisible="{Binding IsWorkOut}"
                                                            Tapped="QueueItemMultiSelectTapped"
                                                            TappedParameter="{Binding .}">
                                                            <ffimage:CachedImage
                                                                Aspect="AspectFill"
                                                                BitmapOptimizations="True"
                                                                DownsampleToViewSize="True"
                                                                RetryCount="6"
                                                                RetryDelay="400"
                                                                Source="{Binding ImageURL}"
                                                                VerticalOptions="FillAndExpand" />
                                                        </controls:TappableFrame>

                                                        <controls:TappableGrid
                                                            Grid.Row="0"
                                                            Grid.Column="1"
                                                            Tapped="QueueItemMultiSelectTapped"
                                                            TappedParameter="{Binding .}"
                                                            VerticalOptions="CenterAndExpand">
                                                            <Grid.ColumnDefinitions>
                                                                <ColumnDefinition Width="Auto" />
                                                                <ColumnDefinition Width="*" />
                                                                <ColumnDefinition Width="10" />
                                                            </Grid.ColumnDefinitions>
                                                            <Grid.RowDefinitions>
                                                                <RowDefinition Height="Auto" />
                                                                <RowDefinition Height="Auto" />
                                                            </Grid.RowDefinitions>

                                                            <Label
                                                                Grid.Row="0"
                                                                Grid.Column="0"
                                                                HorizontalOptions="FillAndExpand"
                                                                IsVisible="{Binding Video.IsNotWorkout}"
                                                                LineBreakMode="TailTruncation"
                                                                Text="{Binding Video.VideoName}" />

                                                            <Label
                                                                Grid.Row="0"
                                                                Grid.Column="0"
                                                                Margin="0,10,0,0"
                                                                HorizontalOptions="FillAndExpand"
                                                                IsVisible="{Binding IsWorkOut}"
                                                                LineBreakMode="TailTruncation"
                                                                Text="{Binding Name}" />

                                                            <controls:TappableImageButton
                                                                Grid.Row="0"
                                                                Grid.Column="1"
                                                                Margin="0,10,0,0"
                                                                HeightRequest="20"
                                                                HorizontalOptions="EndAndExpand"
                                                                IsVisible="{Binding IsWorkOut}"
                                                                Source="arrowright"
                                                                TappedCommand="{Binding Source={x:Reference QueueListTapped}, Path=BindingContext.QueueItemTappedCommand}"
                                                                TappedParameter="{Binding .}"
                                                                WidthRequest="20" />

                                                            <controls:TappableStackLayout
                                                                Grid.Row="1"
                                                                Grid.ColumnSpan="2"
                                                                IsVisible="{Binding IsWorkOut}">
                                                                <controls:TappableGrid Tapped="QueueItemMultiSelectTapped" TappedParameter="{Binding .}">
                                                                    <Label
                                                                        Grid.Row="0"
                                                                        Grid.Column="0"
                                                                        HorizontalOptions="FillAndExpand"
                                                                        LineBreakMode="TailTruncation"
                                                                        Text="Created on : " />
                                                                    <Label
                                                                        Grid.Row="0"
                                                                        Grid.Column="1"
                                                                        HorizontalOptions="StartAndExpand"
                                                                        HorizontalTextAlignment="Start"
                                                                        LineBreakMode="TailTruncation"
                                                                        Text="{Binding CreatedOn}" />

                                                                    <Label
                                                                        Grid.Row="1"
                                                                        Grid.Column="0"
                                                                        HorizontalOptions="FillAndExpand"
                                                                        LineBreakMode="TailTruncation"
                                                                        Text="Created by : " />
                                                                    <Label
                                                                        Grid.Row="1"
                                                                        Grid.Column="1"
                                                                        HorizontalOptions="StartAndExpand"
                                                                        HorizontalTextAlignment="Start"
                                                                        LineBreakMode="TailTruncation"
                                                                        Text="{Binding CreatedBy}" />

                                                                    <Label
                                                                        Grid.Row="2"
                                                                        Grid.Column="0"
                                                                        HorizontalOptions="StartAndExpand"
                                                                        Text="{Binding ConvertWorkOutDuration}"
                                                                        VerticalTextAlignment="Center" />

                                                                    <controls:TappableLabel
                                                                        Grid.Row="2"
                                                                        Grid.Column="1"
                                                                        HorizontalOptions="StartAndExpand"
                                                                        Tapped="AbilityLevelTapped"
                                                                        TappedParameter="{Binding .}"
                                                                        Text="{Binding Abilitylevel}"
                                                                        VerticalTextAlignment="Center" />

                                                                    <controls:TappableImageButton
                                                                        Grid.Row="2"
                                                                        Grid.Column="1"
                                                                        HeightRequest="20"
                                                                        HorizontalOptions="EndAndExpand"
                                                                        Source="dots"
                                                                        TappedCommand="{Binding Source={x:Reference CommonContextMenu}, Path=BindingContext.MenuItemCommand}"
                                                                        TappedParameter="{Binding .}"
                                                                        VerticalOptions="Center"
                                                                        WidthRequest="20" />
                                                                </controls:TappableGrid>
                                                            </controls:TappableStackLayout>

                                                            <controls:TappableStackLayout
                                                                Grid.Row="1"
                                                                Grid.ColumnSpan="2"
                                                                IsVisible="{Binding IsNotWorkout}"
                                                                Tapped="QueueItemMultiSelectTapped">
                                                                <controls:TappableGrid Tapped="QueueItemMultiSelectTapped" TappedParameter="{Binding .}">
                                                                    <Label
                                                                        Grid.Row="0"
                                                                        Grid.Column="0"
                                                                        HorizontalOptions="FillAndExpand"
                                                                        IsVisible="{Binding Video.ShowAddToWorkout}"
                                                                        LineBreakMode="TailTruncation"
                                                                        Text="InWorkouts : " />
                                                                    <controls:TappableImageButton
                                                                        Grid.Row="0"
                                                                        Grid.Column="1"
                                                                        HeightRequest="20"
                                                                        HorizontalOptions="StartAndExpand"
                                                                        IsVisible="{Binding Video.ShowAddToWorkout}"
                                                                        Source="addtoworkout"
                                                                        TappedCommand="{Binding Source={x:Reference QueueListTapped}, Path=BindingContext.WorkoutNamesCommand}"
                                                                        TappedParameter="{Binding .}"
                                                                        VerticalOptions="CenterAndExpand"
                                                                        WidthRequest="20" />
                                                                    <Label
                                                                        Grid.Row="1"
                                                                        Grid.ColumnSpan="2"
                                                                        HorizontalOptions="StartAndExpand"
                                                                        HorizontalTextAlignment="Start"
                                                                        LineBreakMode="TailTruncation"
                                                                        Text="{Binding Video.TypeOfExercise}" />

                                                                    <Label
                                                                        Grid.Row="2"
                                                                        Grid.Column="0"
                                                                        HorizontalOptions="StartAndExpand"
                                                                        Text="{Binding Video.ConvertDuration}"
                                                                        VerticalTextAlignment="Center" />

                                                                    <controls:TappableLabel
                                                                        Grid.Row="2"
                                                                        Grid.Column="1"
                                                                        HorizontalOptions="StartAndExpand"
                                                                        Tapped="AbilityLevelTapped"
                                                                        TappedParameter="{Binding .}"
                                                                        Text="{Binding Video.AbilityLevel}"
                                                                        VerticalTextAlignment="Center" />

                                                                    <controls:TappableImageButton
                                                                        Grid.Row="2"
                                                                        Grid.Column="1"
                                                                        HeightRequest="20"
                                                                        HorizontalOptions="EndAndExpand"
                                                                        Source="dots"
                                                                        TappedCommand="{Binding Source={x:Reference CommonContextMenu}, Path=BindingContext.MenuItemCommand}"
                                                                        TappedParameter="{Binding .}"
                                                                        VerticalOptions="Center"
                                                                        WidthRequest="20" />
                                                                </controls:TappableGrid>
                                                            </controls:TappableStackLayout>
                                                        </controls:TappableGrid>
                                                    </helpers:SwipeGesture>
                                                </controls:TappableGrid>
                                            </controls:TappableFrame>
                                            <Frame Grid.Column="1" CornerRadius="5">
                                                <controls:TappableStackLayout
                                                    Margin="0"
                                                    Padding="0"
                                                    Orientation="Horizontal"
                                                    Spacing="5"
                                                    Tapped="RemovefromQueueTapped"
                                                    TappedParameter="{Binding .}"
                                                    VerticalOptions="Center">
                                                    <ffimage:CachedImage
                                                        Margin="-10,0,0,0"
                                                        DownsampleToViewSize="True"
                                                        Source="swdelete" />
                                                    <controls:TappableLabel
                                                        Margin="-5,0,0,0"
                                                        BackgroundColor="White"
                                                        Font="17"
                                                        Tapped="RemovefromQueueTapped"
                                                        TappedParameter="{Binding .}"
                                                        Text="Delete"
                                                        TextColor="Gray"
                                                        VerticalTextAlignment="Center" />
                                                </controls:TappableStackLayout>
                                            </Frame>
                                        </controls:TappableGrid>
                                    </SwipeView>
                                </renderedViews:DraggableViewCell>
                            </DataTemplate>
                        </renderedViews:HorizontalListView.ItemTemplate>
                    </renderedViews:HorizontalListView>
[Swipeview related code.txt](https://github.com/xamarin/Xamarin.Forms/files/4179245/Swipeview.related.code.txt)



Please look in to that and let me know the issue.

**Comment by chinni-nag** [comment]
@samhouts  I checked with Latest xamarin.forms version only(4.4.0).

**Comment by chinni-nag** [comment]
I Did not get you what will i do? Is there any solution for this?

**Comment by chinni-nag** [comment]
@samhouts  Any update on this? Please let me know. Thanks.

**Comment by chinni-nag** [comment]
@samhouts @jsuarezruiz  Any Update on this, Please let me know . Thanks.

**Comment by jsuarezruiz** [comment]
@chinni-nag We are fixing multiple SwipeView issues. This issue will be fixed with the PR: https://github.com/xamarin/Xamarin.Forms/pull/9638 

![fix9466](https://user-images.githubusercontent.com/6755973/75172844-35be5680-572e-11ea-882f-d3116ae0d62d.gif)

**Comment by chinni-nag** [comment]
@jsuarezruiz Thanks for your reply.  Swipableview is working fine  In Ios and android but command parameters and commands not working fine as  i mentioned above screen shot. 
From above Screen shot you can observe that i have  3 dots symbol and small plus icon so those click are not working fine after add swipe view..

**Comment by chinni-nag** [comment]
@jsuarezruiz  Is this bug fixed in 4.5 latest stable version?? Please let me know.

Thanks.

**Comment by chinni-nag** [comment]
@jsuarezruiz  Today only i tried this bug with latest version 4.5 version Xamarin.forms. Every thing is working fine. But  I found below behaviors for both Ios and Android. Attaching the references  to your mail. Please check it once and let me know this . Thanks

**Comment by chinni-nag** [comment]
@jsuarezruiz  Any Update on this? Please let me know. Thanks.

**Comment by jsuarezruiz** [comment]
@chinni-nag This PR https://github.com/xamarin/Xamarin.Forms/pull/9638 will fix theListView selection issue using SwipeView. On the other hand, this other PR https://github.com/xamarin/Xamarin.Forms/pull/9664 will fix issues related with touch conflicts, etc. Both PRs need to pass the validation process (revision etc). I will let you know when we have merged them!.

**Comment by chinni-nag** [comment]
@jsuarezruiz  Thanks for your reply.

**Comment by chinni-nag** [comment]
@jsuarezruiz  Any update on this issue, Please let me know.

**Comment by chinni-nag** [comment]
@jsuarezruiz  Any update on this issue. Please let me know. Thanks.

**Comment by MappingSteve** [comment]
@jsuarezruiz - BTW, according to [this StackOverflow post](https://stackoverflow.com/q/68251572/199364), there is still an issue when ListView > ContentView > SwipeView. Post  says ListView > SwipeView does work, but wrapping a ContentView around the Swipe View caused ListVIew to no longer fire ItemSelected.
