### ISSUE TITLE
AspectFit does not size Image correctly when loaded from Byte Array[Bug] 

### ISSUE THREAD

**Issue by sehuff** [xamarin/Xamarin.Forms#9925]
When I load an image from a ByteArray into a MemoryStream then use ImageSource.FromStream to load it and bind it to an Image tag the Property Aspect does not correctly size the image when set to AspectFit - if you have the image in your iOS Resources and load it it works fine.

I ultimately need to store it in a JSON file as a byte array but I need the AspectFit to work when it's loaded from a byte array the same as if it was local.

- Version with issue: Xamarin.Forms 4.5.0.356
- IDE: Visual Studio For MAC 8.4.8 (build 2)

This screen shot shows the same image, the one on the left is loaded from a local ios resource file the one on the right is the same image loaded as a byte array:
![image](https://user-images.githubusercontent.com/2104761/76350210-ba3dd700-62e1-11ea-8aec-d1b72f0da877.png)

I'm attaching a Zip file with a sample project that shows the issue.  However here is some of the key parts:

`
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using Xamarin.Forms;

namespace ByteArrayImageIssue
{

    [DesignTimeVisible(false)]
    public partial class MainPage : ContentPage
    {
        public class MenuItem
        {
            public string title { get; set; }
            public ImageSource image { get; set; }

            public MenuItem(string title, ImageSource image)
            {
                this.title = title;
                this.image = image;
            }
        }

        public List<MenuItem> MenuItems { get; set; }

        public MainPage()
        {
            InitializeComponent();
            NavigationPage.SetBackButtonTitle(this, "");
            //*****************************
            //*
            //* You can uncomment out the first img var
            //* and comment out the second and get the same result.
            //*
            //*****************************

            //byte[] img = System.Convert.FromBase64String("iVBORw0KGgoAAAANSUhEUgAAAFYAAABRCAYAAABIU1FPAAAAAXNSR0IArs4c6QAADIJJREFUeAHtXAt0TVca/oU83CQSNEUrpGsh9YiKqdAkQxUlMe1anRHKQoNhqOqLeBTjMY1Oq9PpDMroGKqtLAltmRFtSYiJUGZQiUcwaxJRj0TITQgRidnfvs7NPfeee+953TjJ+NdKztl7/2c/vvuff+/9//8+Te4xooekOwJeutf4sEKOwENgPSQIjRJY841K2n/0DBVduuoh2NxX28w9i7E58s4WUfq+YxzI3HPnyXzjlmSHY3uFU4/O7Sm+fyTFRHaR5NEzs0lDnLwgkX/ZnEGbduZQ0eVSxXiEtm1NY+Ki6TejBlFQgEnx83IeaHDArtm8mz5Y/3enkiln0AJPUEBzmpowmGZPekHI0u3aYICFvhw7bzXlnSvSbfBCRT06hdKq+YlMVYQKWZqvDQJYTETj5q3SRUqdIQbpTX59FI2Oj3bGoijf8MCmpOfQa8s2KBqUFuaV7yTqAq6hgYWkvjjjQy04qXpWD3ANCyx06oAJv/Po6+8K9az1CzXpXMNuEDBROVuTugJEr7Kx8z5h7Veqrs6QwGJJ5YnZXwlKWB9jrayWDKcKICWRI+Y9UGm1BfNY2jIKbfeIbZase8NJLKTkQaoAe9TeX/cP+yxZacMBi22qkSg9+6iq7hgKWBhU1Oz9VY1c5kN4e3YyI49SMhSwsFIZkXao6JehgMWGwIiUq8I+YShgYU81IqlZ+tWrobugoJAKCgqouKTEAb+wsDCqrMSCvIlDmREyoP+VWL88DmwJAzE1dQsdOvyv+8A5h+nnbYlu321KP1V408WqZlRdaxyQlS4BPQYsAF2/YSMdZoCC2oY8SjF9+1JERDdq3z6UQsM6WhE+kJ1Nly8V06nT+XQ6P5/8mt2mMAZqgdmXCm95W/ka0o1HgN2xYyelpm3hEhoZ0ZPGjRsjAtIeoGdiY3nWS/cLvk77itK//Z6aepmpjamGjpt9mCQbajqwH4JDWvct7apVq2lv1j4uoWNGJ5AAmkPLbjLMZWW0OSWVdu3ZQzVMeo9dM5H5zoMDV6m1S1dgBVC7du5CM5PeoqDgYDfwuS/e9e139PkXKXTj9p0HCm5p9lr3nbXh0E0E8OpDUvHqL01eoguo6OeQYUMpif1IAX4+1KtVJXl71X9EFLy6SkkXYE+cOElpaVv56//OwnlK++CWP+Kpp2jc2NFM596jyJZVbvn1ZkBMglLSBdgNbPZv7uNLs5PeVtq+bH5Ibmy/vhTgW00dm1fLfk4PxpjeygM8NAO7d28WFRQWUmxMtMuZX48BJk5M5D9gaGD9Ahvfv5fi7msGFksrSOuo0SMVN670AUyG+AF9mtVQO99apY+r4h89LFpVtIwmYPkWlUnrz3r34pPVxcf6Ef5ufGrxrOL+yrA4VQNy9pDwA7Yz3XHGomv+nEm/UFWfJmAxaYGiop4WNX4r44AorWcCUhsWGkqBvnf1rFayLkirGrcMKtO08zpx0gKs/Saget9PVLU/3drZ6twDVJb8ISG/ac+WFPT6K2T+82dUc/w6mabFMt4T5BvTnfML94Ez5lDZ3FlUtT2fvPs/ToHjE8gv/mXO07lTJyooKqIgn1qPbRp4ZMyb6tWbJoktKS7h0mNFkN0AOK+2flR16JA1u2LjBg5q8EcTOZg3t++0lvmwzQSocnU22d6bkxdwUNvk/I2XV2xM41f8e+IJi53B5EEbzefvTVelW4VOagIWqwEp8hkUTlU/5FqLgua/Sy2WjKA7Zy2G7LsFxdYy08tTJO+rc8/z/CvRE/mPAmkXKCDAn98GentGHSASRmsMrSZVIAzU/moaOJCu/fpja/a1qVOp5kwpBUxTPhE8dvEgVyv3zOXW+jx5A72qR2CcJol1NkDoQqgEgbhu7dKafPvFCFlur82H9uU80M/lK9aRrSpw+7BKBkjqygWJKp8WP6YJ2LCOdTZVcbVknYyQH5A0jL/ON7/ZyvWvV7D7KGr/CdPJ98VwKhn6FtWWVVLw/Fn2TVBVjT5KFhPV9hWzdJFUoZOarFuLFi+lkydPUVpqilBfvVzXrl7LzYnHSv3pWpUm2SC8+sls9tc7ZF5Tr7p378aBzP3xx3oBVGjkwgXLRFbjbZnEhHy5V0goAEX4EF59AVR4ieHb0oM0TV5Rffpwq1Zmxh6CBao+CAZwrEb69Hma0pJm8mAK+P3honblTYXpD1YqGFSw9xfARJ8RkLEmNYOyj+XzIcTH9qJlb4xUvTlAJZqADWN+q5CQRyjvxGneofr4l7krk27dqWK+s568uTgGEv4EgsTZOv4gnVLeVQTfpezIoTVpGQ7RN+nZ7HgTA3n2hBdo6qjBQtWKrpp0LFqCgRu22DEJCfRSwi8VNa6GefKkqVTKll45xf40JDqSS18sO7clZ+uJYOZs9roj4gbgySFIr626kPMMeDQDe/NmJb06fQbdu1tDK1Z+rJvnQGoAX372BX2zYwddKPelMzd8RCzCq96hXWuKYKdfWgSaqLyiknKZBPM/pirUxoXhVM32lTNF6kPUuERCM7CoEzEDy5f/geDrglvGE4QJcmny73ncQU6x++Wa3n2ASoFDUc6bgbY1rQqEzkexieTZAf3pFNuyYimkN2HCWr78j9xbe6LMT+/qZdUHvW0J36+Uxa8LsGgpMfEVwoYB7uo/fVS3nZXVCxdMkNQF8xfxCQsBHA/SBY5Vx/i5q130tq5IF1UgVAd9+8abb5PZbOZqQasLXHB9YxXwn+t+homKmcNWC+6OieoKLDwKSbPnCjhzlw1cKbD6K4kxQMjRV19v5zZXIwRrWAdkc+MugENXYJOS5vLFu037/BY+sSfDw9mivjdFMU+rFMh45Y8fy6WDhw7T5RKLWfHqTW86VeFrqOA4YWzYbGxjKwVnpAnYjN2ZNGjwc7xuYT1r31Bc3FA6dfK0A+Bwr4DKysqprMJsfQwSev1WMzpz0/jxWq5OMKoGdtOXKeTVtClVlFfQc4MG0tx5863gCDfdunWlJYt/y5OIPoSP7L9MXWxLz6KqqjoX9l3mcL1R7UVXq5tpNqoIbdfHFevbrA0LJZtStaXNy83joKLGwBaBlJOTQ20fbUOXi69YGzGZTPTa9GnWdEhICD377AC6xXY9/7yYzfKbWssa6g1WCc4CklUttzIyMkVYeHv7UExsNEVHRTGfvyWedWTCCGZHCBHxIbGJneZuTLTGyelFxcBCl2bnHKDc43kO+LRr/zgNi3ueenTtRsOHS8cTyN2jO1Ru0Axn58AUAQs9icgX0JlzZ2n3rt10vfSaaMiQ3vCu4fTp2nVUWHheVGbUUzGiTipMYEcmZcNVBOxKFlRsOYBhad1cUUGZWVmS0gvd+/13u0Td3H/EYu8UZTaCRLbEuGQDC0mFG0aKnEnv80OHiNgbo8RigHlnL4jGiYQsYKECoFtdkb301tbUUMeOHUSPFF6+Kko3loSUOVLWcsteBbgCBNJLVEvJy951YJPqgANTA8yQOvjnVmJdqQBnGEyeMtlZUaPMt3UFCQN0CawcFSBUJFwTEn5F8IXZk9TMac/TmNIugVWiAgAK7LHYGEiR1K8qxddY8pwCq0YFTLfZwjYWgNSOQxJYGKzdrQLsG3SmAgS+Dm1bCbf/F1dJYFd9It4IuEPClQoQnpXrhBP4G/rVAVh4XIWDxXIHJ1cFqDmIJrcPD5JP6hyYCFioABzbVELx8XGSqwCpOlbNnyCV3eDzklk4kj2JgFWqAhBe5GwVYN8Q0oiShtW9MRHGIxXCZAUWbpZAkz8FBQbKHvf0V6eRv7+y4AlESyMWFQEQDZmg1uBQdBb9zYEtYwERFy9dpJatW9HgIYOpS6fObscMFSCEcbpltmOA5B7d8h772vAguxLjJyEQcH/DJSMlqcIIuM9r3V/Xk3+AONYUdtZ/HzlCMK7YE1TA8g/eVyyt9vUgjUA1hFCmsA+ZGXkTAUDx2Wm53/XmwEJi01K3cv+V/eDhKbAYVupKFi9aqFpa62pxvEOcKmJdYZU3AsgAMz42kobbhYo69twxR+SlhZ6FSoAXwJZspRcqYELieNtij9zDdgvDuNZIQSWdg96MYJ5XqKrY3vi8v/pvdouARSdcSW/+qXyaNXumLipAyYDBi0BhGJTPM9VRdKmUA17O3CJlyGfeUrkkrDkBIkI+Q9lfB/a1Ta3nuuzbdwBWYJCSXuyw+j3TV2Ax5FX4AYTO6Q2YUK+7q1Ng8SCkdxuLofJt7scDMyZPmeSuvofl9xFwCayA0sEDP9CTzPMarMPHc4Q6G/tVFrCNHQRPjO9/3Icmt60rK2YAAAAASUVORK5CYII=");
            byte[] img= System.Convert.FromBase64String(Convert.ToBase64String(File.ReadAllBytes("name_search2.png")));

            var insuredNameImg = new MemoryStream(img);
                 
            MenuItems= new List<MenuItem>
            {
                //*****************************
                //*
                //* These should show as the same size images
                //* but the one that is FromStream sizes samler with AspectFit selected.
                //*
                //*****************************
                new MenuItem("File Sample", ImageSource.FromFile("name_search2.png")),                
                new MenuItem("Stream Sample", ImageSource.FromStream(() => insuredNameImg))                             
            };

            CV.BindingContext = this;

        }
        void Handle_Tapped(object sender, System.EventArgs e)
        {
            DisplayAlert("Alert", "MenuItem Selected", "OK");
        }
    }
}
`
Here is the XAML:

`
<?xml version="1.0" encoding="UTF-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="ByteArrayImageIssue.MainPage">

    <StackLayout x:Name="SL" BackgroundColor="#F0F0F0">
        <Frame BorderColor="White" CornerRadius="0" Padding = "0" HasShadow="true" BackgroundColor="White">
            <StackLayout VerticalOptions="End" HeightRequest="70"
                         BackgroundColor="White" >
                <StackLayout Orientation="Horizontal" HorizontalOptions="CenterAndExpand" Padding="50">
                    <Label>Header</Label>
                </StackLayout>
            </StackLayout>
        </Frame>
        <CollectionView x:Name="CV" 
                            ItemsSource="{Binding MenuItems}" 
                            VerticalOptions="Center" 
                            HorizontalOptions="Center" 
                            Margin="10,0,10,0" 
                            SelectionMode="Single">
            <CollectionView.ItemsLayout>
                <GridItemsLayout Orientation="Vertical" Span="2"/>
            </CollectionView.ItemsLayout>
            <CollectionView.ItemTemplate>
                <DataTemplate>
                    <Frame Padding="15" BorderColor="#F0F0F0" HasShadow="False" BackgroundColor="#F0F0F0">
                        <Frame BorderColor="White" CornerRadius="3" HasShadow="true" BackgroundColor="White" ClassId="{Binding title}">
                            <Frame.GestureRecognizers>
                                <TapGestureRecognizer Tapped="Handle_Tapped" NumberOfTapsRequired="1">
                                </TapGestureRecognizer>
                            </Frame.GestureRecognizers>
                            <StackLayout Grid.Column="0" Spacing="5">
                                <Image Source="{Binding image}" Aspect="AspectFit" HeightRequest="100" HorizontalOptions="Center" VerticalOptions="Center"/>
                                <Label Text="{Binding title}" FontSize="Small" HorizontalOptions="CenterAndExpand" VerticalOptions="End" TextColor="#295184" />
                            </StackLayout>
                        </Frame>
                    </Frame>
                </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>
        <Frame BorderColor="White" CornerRadius="0" Padding = "0" HasShadow="true" BackgroundColor="White">
            <StackLayout VerticalOptions="End" HeightRequest="70"
                         BackgroundColor="White" >
                <StackLayout Orientation="Horizontal" HorizontalOptions="CenterAndExpand" Padding="7">
                    <Label>Footer</Label>
                </StackLayout>
            </StackLayout>
        </Frame>
    </StackLayout>
</ContentPage>

`

[ByteArrayImageIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/4314321/ByteArrayImageIssue.zip)

**Comment by PureWeen** [comment]
This should be fixed in an upcoming release

https://github.com/xamarin/Xamarin.Forms/pull/9662

**Comment by sehuff** [comment]
> This should be fixed in an upcoming release
> 
> #9662

I don't see a direct correlation between this and #9662 but since they both deal with images and sizing I guess it's possible.  Will this fix be in the next service release and is there an ETA?  Thx for the quick response.

**Comment by sehuff** [comment]
I also found that if i write the ByteArray back to the AppDataDirectory and display it from that, the image is sized correctly which is my work around for now.

**Comment by jfversluis** [comment]
Tried this with the latest nightly which should have the fix of the mentioned PR included, unfortunately that does not fix it
